### ISSUE TITLE
Open door crash

### ISSUE THREAD

**Issue by twigsta** [jrbudda/Vivecraft_110#10]
When I walk through an open doorway, it sometimes crashes.

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 20/07/16 18:42
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at ali.c(SourceFile:242)
	at ali.b(SourceFile:89)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.canStand(OpenVRPlayer.java:817)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.checkAndSetTeleportDestination(OpenVRPlayer.java:750)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportArc(OpenVRPlayer.java:636)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportDestinations(OpenVRPlayer.java:674)
	at bnz.getPointedBlock(EntityRenderer.java:3488)
	at bnz.b(EntityRenderer.java:1545)
	at bnz.updateCameraAndRender(EntityRenderer.java:1321)
	at bcx.renderSingleView(Minecraft.java:4866)
	at bcx.av(Minecraft.java:1501)
	at bcx.a(Minecraft.java:652)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at ali.c(SourceFile:242)
	at ali.b(SourceFile:89)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.canStand(OpenVRPlayer.java:817)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.checkAndSetTeleportDestination(OpenVRPlayer.java:750)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportArc(OpenVRPlayer.java:636)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportDestinations(OpenVRPlayer.java:674)
	at bnz.getPointedBlock(EntityRenderer.java:3488)
	at bnz.b(EntityRenderer.java:1545)
	at bnz.updateCameraAndRender(EntityRenderer.java:1321)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bnn['twigste'/254, l='MpServer', x=-113.18, y=98.83, z=95.94]]
	Chunk stats: MultiplayerChunkCache: 602, 602
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-256,64,144), Chunk: (at 0,4,0 in -16,9; contains blocks -256,0,144 to -241,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 25654 game time, 25654 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 123 total; [yk['item.item.coal'/6400, l='MpServer', x=-106.13, y=72.00, z=134.88], zi['Zombie'/6913, l='MpServer', x=-143.50, y=20.00, z=163.50], wa['Bat'/9218, l='MpServer', x=-101.58, y=22.56, z=154.71], yk['item.tile.dirt.coarse'/9222, l='MpServer', x=-111.73, y=97.00, z=104.18], zi['Zombie'/8460, l='MpServer', x=-75.50, y=36.00, z=132.50], wa['Bat'/8211, l='MpServer', x=-161.25, y=28.78, z=160.16], wa['Bat'/8213, l='MpServer', x=-157.43, y=29.09, z=157.43], wa['Bat'/8216, l='MpServer', x=-75.81, y=37.16, z=131.25], zi['Zombie'/8988, l='MpServer', x=-35.50, y=59.00, z=61.50], yq['Enderman'/8989, l='MpServer', x=-36.50, y=59.00, z=60.50], yq['Enderman'/8990, l='MpServer', x=-34.50, y=59.00, z=60.50], yq['Enderman'/8991, l='MpServer', x=-34.50, y=59.00, z=59.50], yp['Creeper'/8492, l='MpServer', x=-152.50, y=24.00, z=63.50], zi['Zombie'/8493, l='MpServer', x=-39.50, y=26.00, z=158.50], wa['Bat'/8496, l='MpServer', x=-150.67, y=62.11, z=104.61], yk['item.tile.dirt.coarse'/3123, l='MpServer', x=-125.75, y=70.00, z=121.59], wa['Bat'/5683, l='MpServer', x=-94.45, y=29.10, z=100.75], bnn['twigste'/254, l='MpServer', x=-113.18, y=98.83, z=95.94], yk['item.tile.dirt.default'/3125, l='MpServer', x=-124.34, y=69.00, z=121.53], yk['item.tile.dirt.coarse'/3126, l='MpServer', x=-120.83, y=70.00, z=120.88], wa['Bat'/9271, l='MpServer', x=-34.05, y=42.73, z=99.53], yk['item.tile.dirt.default'/3128, l='MpServer', x=-123.13, y=68.00, z=119.13], yk['item.tile.dirt.coarse'/3132, l='MpServer', x=-125.19, y=69.00, z=120.57], yk['item.tile.dirt.coarse'/3133, l='MpServer', x=-123.63, y=68.00, z=120.88], yp['Creeper'/9533, l='MpServer', x=-42.50, y=27.00, z=144.50], yp['Creeper'/7998, l='MpServer', x=-71.50, y=22.00, z=94.50], zd['Skeleton'/8766, l='MpServer', x=-34.50, y=19.00, z=146.50], yk['item.tile.dirt.coarse'/3135, l='MpServer', x=-123.82, y=68.00, z=119.24], yk['item.item.arrow'/6720, l='MpServer', x=-168.31, y=69.00, z=42.80], zi['Zombie'/8256, l='MpServer', x=-48.50, y=37.00, z=130.50], yp['Creeper'/8257, l='MpServer', x=-47.50, y=37.00, z=131.50], yk['item.item.bone'/6721, l='MpServer', x=-169.14, y=69.00, z=41.92], yk['item.tile.dirt.default'/8262, l='MpServer', x=-109.23, y=88.00, z=103.82], yp['Creeper'/7496, l='MpServer', x=-192.50, y=24.00, z=58.50], wa['Bat'/4426, l='MpServer', x=-97.77, y=18.04, z=170.09], wa['Bat'/9551, l='MpServer', x=-103.72, y=21.34, z=160.53], bnn['twigste'/254, l='MpServer', x=-121.50, y=71.00, z=117.77], we['Cow'/3931, l='MpServer', x=-35.80, y=68.00, z=58.39], zd['Skeleton'/9307, l='MpServer', x=-160.50, y=21.00, z=137.50], we['Cow'/3932, l='MpServer', x=-38.54, y=68.00, z=58.70], zi['Zombie'/8540, l='MpServer', x=-176.50, y=12.00, z=165.50], we['Cow'/3933, l='MpServer', x=-46.19, y=70.00, z=51.54], we['Cow'/3934, l='MpServer', x=-36.24, y=67.00, z=61.57], zi['Zombie'/7521, l='MpServer', x=-62.34, y=63.00, z=159.41], zi['Zombie'/7523, l='MpServer', x=-65.65, y=63.00, z=154.35], yp['Creeper'/8035, l='MpServer', x=-176.50, y=31.00, z=161.50], yp['Creeper'/8037, l='MpServer', x=-102.50, y=37.00, z=81.50], wa['Bat'/4966, l='MpServer', x=-177.75, y=28.10, z=115.81], we['Cow'/3942, l='MpServer', x=-36.50, y=72.00, z=115.55], we['Cow'/3943, l='MpServer', x=-34.51, y=70.00, z=107.84], we['Cow'/3945, l='MpServer', x=-36.50, y=72.00, z=114.62], zd['Skeleton'/8555, l='MpServer', x=-34.50, y=40.00, z=100.50], zd['Skeleton'/8048, l='MpServer', x=-71.74, y=37.00, z=129.30], zd['Skeleton'/8050, l='MpServer', x=-77.50, y=43.00, z=171.50], yp['Creeper'/6273, l='MpServer', x=-83.50, y=41.00, z=115.50], yk['item.item.spiderEye'/5252, l='MpServer', x=-125.50, y=69.00, z=118.36], zd['Skeleton'/9612, l='MpServer', x=-104.50, y=65.00, z=159.50], zd['Skeleton'/9613, l='MpServer', x=-104.50, y=65.00, z=158.50], wl['Sheep'/149, l='MpServer', x=-164.23, y=66.00, z=140.48], wl['Sheep'/150, l='MpServer', x=-171.53, y=65.00, z=146.76], yp['Creeper'/7581, l='MpServer', x=-89.50, y=34.00, z=175.50], zd['Skeleton'/9630, l='MpServer', x=-93.50, y=24.00, z=125.50], zd['Skeleton'/9119, l='MpServer', x=-154.50, y=29.00, z=160.50], wl['Sheep'/160, l='MpServer', x=-165.27, y=64.00, z=133.48], zi['Zombie'/7591, l='MpServer', x=-118.50, y=44.00, z=56.50], wl['Sheep'/171, l='MpServer', x=-146.25, y=69.00, z=150.50], we['Cow'/172, l='MpServer', x=-136.42, y=86.00, z=130.08], zd['Skeleton'/8366, l='MpServer', x=-161.50, y=28.00, z=151.50], zd['Skeleton'/9391, l='MpServer', x=-34.50, y=42.00, z=92.50], zd['Skeleton'/9392, l='MpServer', x=-33.50, y=42.00, z=93.50], yp['Creeper'/9393, l='MpServer', x=-34.50, y=42.00, z=87.50], yp['Creeper'/7861, l='MpServer', x=-89.50, y=27.00, z=94.50], zi['Zombie'/8117, l='MpServer', x=-47.50, y=41.00, z=121.50], we['Cow'/185, l='MpServer', x=-117.82, y=100.00, z=96.51], we['Cow'/186, l='MpServer', x=-112.78, y=78.00, z=122.47], yk['item.tile.stonebrick'/5818, l='MpServer', x=-109.88, y=72.00, z=135.69], wn['Squid'/8637, l='MpServer', x=-125.01, y=60.24, z=77.05], wi['Pig'/190, l='MpServer', x=-139.31, y=72.00, z=123.46], wn['Squid'/8638, l='MpServer', x=-127.26, y=62.32, z=81.64], we['Cow'/191, l='MpServer', x=-131.21, y=86.00, z=131.47], wn['Squid'/8639, l='MpServer', x=-125.87, y=62.50, z=74.66], wn['Squid'/8640, l='MpServer', x=-161.40, y=59.00, z=87.62], wn['Squid'/8641, l='MpServer', x=-162.71, y=62.53, z=88.14], zi['Zombie'/9153, l='MpServer', x=-71.50, y=64.00, z=160.50], wn['Squid'/8642, l='MpServer', x=-161.96, y=60.79, z=90.91], wn['Squid'/8643, l='MpServer', x=-161.40, y=59.00, z=86.81], wn['Squid'/8644, l='MpServer', x=-91.21, y=61.82, z=88.40], yp['Creeper'/9156, l='MpServer', x=-183.50, y=16.00, z=47.50], wn['Squid'/8645, l='MpServer', x=-87.12, y=61.45, z=88.40], wn['Squid'/8646, l='MpServer', x=-91.11, y=61.00, z=88.40], wn['Squid'/8647, l='MpServer', x=-87.25, y=62.59, z=92.73], wa['Bat'/9160, l='MpServer', x=-64.04, y=16.08, z=124.36], we['Cow'/202, l='MpServer', x=-105.47, y=80.00, z=103.83], we['Cow'/204, l='MpServer', x=-107.55, y=77.00, z=115.43], wi['Pig'/205, l='MpServer', x=-125.66, y=95.00, z=101.51], we['Cow'/206, l='MpServer', x=-123.70, y=83.00, z=139.84], wi['Pig'/207, l='MpServer', x=-93.79, y=84.00, z=141.28], we['Cow'/208, l='MpServer', x=-92.80, y=84.00, z=137.61], yk['item.item.coal'/6354, l='MpServer', x=-107.13, y=71.00, z=133.60], yp['Creeper'/8917, l='MpServer', x=-84.55, y=36.00, z=157.21], zd['Skeleton'/8919, l='MpServer', x=-90.27, y=39.00, z=162.47], yk['item.tile.log.acacia'/3288, l='MpServer', x=-123.15, y=69.00, z=121.88], zd['Skeleton'/9434, l='MpServer', x=-64.50, y=63.00, z=161.50], yk['item.item.doorOak'/3291, l='MpServer', x=-124.88, y=70.00, z=122.73], zd['Skeleton'/9435, l='MpServer', x=-70.54, y=62.69, z=149.49], wi['Pig'/220, l='MpServer', x=-93.22, y=82.00, z=134.50], zd['Skeleton'/9436, l='MpServer', x=-64.50, y=63.00, z=159.50], yk['item.tile.log.oak'/3293, l='MpServer', x=-118.78, y=70.00, z=121.09], we['Cow'/221, l='MpServer', x=-97.41, y=81.00, z=127.21], zd['Skeleton'/9181, l='MpServer', x=-79.50, y=14.00, z=108.50], zd['Skeleton'/9437, l='MpServer', x=-65.50, y=63.00, z=161.50], we['Cow'/222, l='MpServer', x=-102.18, y=83.00, z=143.48], we['Cow'/223, l='MpServer', x=-101.17, y=84.00, z=144.53], yk['item.item.stick'/3297, l='MpServer', x=-126.65, y=71.00, z=120.01], zd['Skeleton'/9185, l='MpServer', x=-137.50, y=23.00, z=65.50], yk['item.tile.stonebrick'/3298, l='MpServer', x=-119.13, y=72.00, z=115.13], zd['Skeleton'/7410, l='MpServer', x=-177.50, y=34.00, z=40.50], we['Cow'/3830, l='MpServer', x=-57.83, y=70.00, z=91.83], we['Cow'/3831, l='MpServer', x=-60.50, y=68.00, z=103.50], we['Cow'/3832, l='MpServer', x=-61.53, y=69.00, z=101.19], we['Cow'/3833, l='MpServer', x=-59.09, y=68.00, z=105.84], yk['item.item.arrow'/7165, l='MpServer', x=-100.89, y=69.00, z=44.56], yk['item.item.bone'/7166, l='MpServer', x=-102.35, y=69.00, z=44.13]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at bln.a(WorldClient.java:496)
	at bcx.b(Minecraft.java:3297)
	at bcx.a(Minecraft.java:681)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 162495704 bytes (154 MB) / 825311232 bytes (787 MB) up to 2120679424 bytes (2022 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: vivecraft-1.10.2-Vivecraft-jrbudda-1
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.81, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: ChromaHills128x-1.9-v.1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 368.81
	OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by jrbudda** [comment]
Oh thats a neat one. See if the r1 release I just put out fixes it.

**Comment by twigsta** [comment]
Nope sorry :(

**Comment by jrbudda** [comment]
could you post the crash message with 1r1? thanks.

**Comment by twigsta** [comment]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 20/07/16 21:31
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at ali.c(SourceFile:242)
	at ali.b(SourceFile:89)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.canStand(OpenVRPlayer.java:817)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.checkAndSetTeleportDestination(OpenVRPlayer.java:750)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportArc(OpenVRPlayer.java:636)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportDestinations(OpenVRPlayer.java:674)
	at bnz.getPointedBlock(EntityRenderer.java:3488)
	at bnz.b(EntityRenderer.java:1545)
	at bnz.updateCameraAndRender(EntityRenderer.java:1321)
	at bcx.renderSingleView(Minecraft.java:4817)
	at bcx.av(Minecraft.java:1501)
	at bcx.a(Minecraft.java:652)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at ali.c(SourceFile:242)
	at ali.b(SourceFile:89)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.canStand(OpenVRPlayer.java:817)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.checkAndSetTeleportDestination(OpenVRPlayer.java:750)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportArc(OpenVRPlayer.java:636)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportDestinations(OpenVRPlayer.java:674)
	at bnz.getPointedBlock(EntityRenderer.java:3488)
	at bnz.b(EntityRenderer.java:1545)
	at bnz.updateCameraAndRender(EntityRenderer.java:1321)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bnn['twigste'/250, l='MpServer', x=-113.67, y=98.79, z=95.90]]
	Chunk stats: MultiplayerChunkCache: 577, 577
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-256,64,144), Chunk: (at 0,4,0 in -16,9; contains blocks -256,0,144 to -241,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 27706 game time, 27706 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 93 total; [we['Cow'/277, l='MpServer', x=-46.34, y=70.00, z=40.81], yq['Enderman'/280, l='MpServer', x=-37.43, y=59.00, z=68.53], yq['Enderman'/281, l='MpServer', x=-40.70, y=60.00, z=54.59], we['Cow'/282, l='MpServer', x=-35.80, y=68.00, z=58.39], we['Cow'/283, l='MpServer', x=-36.40, y=67.00, z=62.18], yp['Creeper'/285, l='MpServer', x=-35.17, y=42.00, z=90.49], zd['Skeleton'/286, l='MpServer', x=-34.50, y=40.00, z=100.50], wa['Bat'/542, l='MpServer', x=-64.25, y=43.00, z=168.50], zd['Skeleton'/287, l='MpServer', x=-35.47, y=41.00, z=97.27], we['Cow'/288, l='MpServer', x=-38.39, y=70.00, z=97.78], we['Cow'/289, l='MpServer', x=-36.50, y=72.00, z=115.55], we['Cow'/290, l='MpServer', x=-36.50, y=72.00, z=114.58], yp['Creeper'/291, l='MpServer', x=-44.50, y=31.00, z=139.50], yp['Creeper'/292, l='MpServer', x=-47.50, y=37.00, z=131.50], bnn['twigste'/250, l='MpServer', x=-113.67, y=98.79, z=95.90], yp['Creeper'/127, l='MpServer', x=-184.17, y=18.00, z=49.47], zd['Skeleton'/129, l='MpServer', x=-180.50, y=30.00, z=57.50], yp['Creeper'/130, l='MpServer', x=-176.50, y=31.00, z=161.50], yk['item.item.arrow'/139, l='MpServer', x=-168.31, y=69.00, z=42.80], yk['item.item.bone'/140, l='MpServer', x=-169.14, y=69.00, z=41.92], wl['Sheep'/141, l='MpServer', x=-165.27, y=64.00, z=133.48], wa['Bat'/142, l='MpServer', x=-161.33, y=28.92, z=159.21], wl['Sheep'/143, l='MpServer', x=-169.50, y=65.00, z=136.62], yp['Creeper'/148, l='MpServer', x=-152.50, y=24.00, z=63.50], zh['Witch'/149, l='MpServer', x=-150.50, y=62.00, z=106.50], wl['Sheep'/150, l='MpServer', x=-156.56, y=70.00, z=136.75], zd['Skeleton'/151, l='MpServer', x=-154.50, y=29.00, z=160.50], wa['Bat'/152, l='MpServer', x=-160.75, y=30.45, z=158.85], wi['Pig'/155, l='MpServer', x=-139.31, y=72.00, z=123.46], we['Cow'/156, l='MpServer', x=-138.16, y=86.00, z=129.60], wl['Sheep'/157, l='MpServer', x=-135.50, y=72.00, z=146.73], yp['Creeper'/169, l='MpServer', x=-123.50, y=23.00, z=57.50], yp['Creeper'/170, l='MpServer', x=-116.80, y=44.00, z=55.44], zi['Zombie'/171, l='MpServer', x=-115.50, y=40.00, z=67.50], wn['Squid'/172, l='MpServer', x=-125.40, y=62.00, z=82.60], we['Cow'/173, l='MpServer', x=-116.69, y=100.00, z=92.67], wi['Pig'/174, l='MpServer', x=-116.74, y=100.00, z=93.67], we['Cow'/175, l='MpServer', x=-112.60, y=78.00, z=121.81], yk['item.item.spiderEye'/176, l='MpServer', x=-125.50, y=69.00, z=118.36], zd['Skeleton'/177, l='MpServer', x=-118.08, y=27.00, z=143.50], we['Cow'/178, l='MpServer', x=-119.62, y=84.00, z=137.45], we['Cow'/179, l='MpServer', x=-125.45, y=84.00, z=135.42], yk['item.item.arrow'/182, l='MpServer', x=-100.89, y=69.00, z=44.56], yk['item.item.bone'/183, l='MpServer', x=-102.35, y=69.00, z=44.13], yp['Creeper'/184, l='MpServer', x=-103.73, y=36.00, z=81.48], yk['item.tile.dirt.default'/185, l='MpServer', x=-109.23, y=88.00, z=103.82], we['Cow'/186, l='MpServer', x=-110.52, y=84.00, z=110.41], we['Cow'/187, l='MpServer', x=-109.22, y=76.00, z=116.66], we['Cow'/188, l='MpServer', x=-97.41, y=81.00, z=127.21], yk['item.tile.stonebrick'/189, l='MpServer', x=-109.88, y=72.00, z=135.69], yk['item.item.coal'/190, l='MpServer', x=-107.13, y=71.00, z=133.60], yk['item.item.coal'/191, l='MpServer', x=-106.13, y=72.00, z=134.88], wi['Pig'/192, l='MpServer', x=-98.83, y=81.00, z=130.14], zi['Zombie'/193, l='MpServer', x=-113.50, y=47.00, z=161.28], zd['Skeleton'/194, l='MpServer', x=-105.50, y=66.00, z=151.77], zd['Skeleton'/195, l='MpServer', x=-105.52, y=64.00, z=162.28], we['Cow'/196, l='MpServer', x=-101.17, y=84.00, z=144.53], zi['Zombie'/197, l='MpServer', x=-107.50, y=20.00, z=163.50], yp['Creeper'/209, l='MpServer', x=-89.50, y=27.00, z=94.50], wn['Squid'/210, l='MpServer', x=-86.60, y=61.00, z=92.60], wn['Squid'/211, l='MpServer', x=-95.60, y=61.00, z=85.40], wn['Squid'/212, l='MpServer', x=-95.13, y=61.00, z=88.60], yp['Creeper'/213, l='MpServer', x=-83.50, y=41.00, z=115.50], zd['Skeleton'/214, l='MpServer', x=-79.72, y=45.00, z=140.49], wi['Pig'/215, l='MpServer', x=-92.87, y=84.00, z=140.84], we['Cow'/216, l='MpServer', x=-96.49, y=81.00, z=128.83], we['Cow'/217, l='MpServer', x=-93.91, y=84.00, z=141.71], zd['Skeleton'/218, l='MpServer', x=-81.50, y=36.00, z=155.50], wa['Bat'/219, l='MpServer', x=-101.06, y=19.94, z=166.87], zd['Skeleton'/220, l='MpServer', x=-90.27, y=39.00, z=162.47], wa['Bat'/221, l='MpServer', x=-89.31, y=35.10, z=172.36], zd['Skeleton'/222, l='MpServer', x=-83.50, y=36.00, z=160.50], zi['Zombie'/228, l='MpServer', x=-69.50, y=22.00, z=94.50], zd['Skeleton'/229, l='MpServer', x=-79.50, y=14.00, z=108.50], yp['Creeper'/230, l='MpServer', x=-66.52, y=24.00, z=97.21], yp['Creeper'/231, l='MpServer', x=-66.50, y=14.00, z=122.50], yp['Creeper'/232, l='MpServer', x=-72.50, y=14.00, z=113.50], zd['Skeleton'/233, l='MpServer', x=-73.36, y=36.00, z=129.42], zi['Zombie'/234, l='MpServer', x=-75.50, y=36.00, z=132.50], wa['Bat'/235, l='MpServer', x=-64.36, y=42.10, z=140.25], zd['Skeleton'/236, l='MpServer', x=-72.50, y=37.00, z=135.50], zi['Zombie'/237, l='MpServer', x=-72.50, y=36.00, z=130.50], zi['Zombie'/238, l='MpServer', x=-73.50, y=36.00, z=130.50], zi['Zombie'/239, l='MpServer', x=-70.49, y=64.00, z=153.80], zd['Skeleton'/240, l='MpServer', x=-78.50, y=37.00, z=165.50], zi['Zombie'/241, l='MpServer', x=-72.50, y=59.00, z=166.20], zg['Spider'/242, l='MpServer', x=-68.70, y=66.10, z=166.91], we['Cow'/244, l='MpServer', x=-57.83, y=70.00, z=91.83], we['Cow'/245, l='MpServer', x=-60.50, y=68.00, z=103.50], we['Cow'/246, l='MpServer', x=-61.53, y=69.00, z=101.19], we['Cow'/247, l='MpServer', x=-54.44, y=69.00, z=106.78], yp['Creeper'/248, l='MpServer', x=-49.50, y=26.00, z=166.50], zd['Skeleton'/249, l='MpServer', x=-63.67, y=63.00, z=160.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at bln.a(WorldClient.java:496)
	at bcx.b(Minecraft.java:3299)
	at bcx.a(Minecraft.java:681)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 548830264 bytes (523 MB) / 992251904 bytes (946 MB) up to 2120679424 bytes (2022 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: vivecraft-1.10.2-Vivecraft-jrbudda-1r1
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.81, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: ChromaHills128x-1.9-v.1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 4
	Antialiasing: 0
	Multitexture: true
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 368.81
	OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by jrbudda** [comment]
should do it.

[vivecraft-1.10.2-Vivecraft-jrbudda-1r11-installer.zip](https://github.com/jrbudda/Vivecraft_110/files/374813/vivecraft-1.10.2-Vivecraft-jrbudda-1r11-installer.zip)

**Comment by jrbudda** [comment]
Should actually do it for all cases.

[vivecraft-1.10.2-Vivecraft-jrbudda-1r2-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/374846/vivecraft-1.10.2-Vivecraft-jrbudda-1r2-installer.exe.zip)
