### ISSUE TITLE
Installer Crashing Instantly

### ISSUE THREAD

**Issue by IAMCHIDDYBANG** [jrbudda/Vivecraft_110#100]
I don't really know what to do at this point as it just seems to not want to run what-so-ever even though this used to run fine. It keeps making these error logs though so hopefully y'all can see what I can't.

Windows 10

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbf722fd0c, pid=14692, tid=0x00000000000017b4
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [d3d9.dll+0xfd0c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x000000001fb06800):  JavaThread "AWT-Windows" daemon [_thread_in_native, id=6068, stack(0x0000000020460000,0x0000000020560000)]

siginfo: ExceptionCode=0xc0000005, writing address 0x0000000000000000

Registers:
RAX=0x0000000000000000, RBX=0x000000002055df60, RCX=0x0000000020779a60, RDX=0x000000002055e770
RSP=0x000000002055deb8, RBP=0x000000002055e250, RSI=0x0000000000000001, RDI=0x0000000020771da0
R8 =0x0000000000000000, R9 =0x0000000000000000, R10=0x000000002077a87c, R11=0x0000000000000246
R12=0x0000000000000000, R13=0x000000002055e770, R14=0x0000000000000000, R15=0x0000000000000000
RIP=0x00007ffbf722fd0c, EFLAGS=0x0000000000010246

Top of Stack: (sp=0x000000002055deb8)
0x000000002055deb8:   00007ffbf723167f 000000002055df18
0x000000002055dec8:   000000002055df20 0000000000000604
0x000000002055ded8:   0000000001030030 0000000000000000
0x000000002055dee8:   0000000020771da0 0000000000000000
0x000000002055def8:   00007ffbf72476a6 0000000000000000
0x000000002055df08:   0000000000000000 0000000000000001
0x000000002055df18:   00007ffc2e90b89a 0000000000000000
0x000000002055df28:   0000000000000000 0000000000005c88
0x000000002055df38:   0000000000005c90 0000000000000000
0x000000002055df48:   000000002055df98 0000000000000000
0x000000002055df58:   000000000000001a 0000000000000000
0x000000002055df68:   0000000000000000 0000000020752000
0x000000002055df78:   0000000020779a60 0000000000000000
0x000000002055df88:   0000000000e31438 0000000000000000
0x000000002055df98:   0000000000000003 0000000000000000
0x000000002055dfa8:   0000000000000000 0000000000000000 

Instructions: (pc=0x00007ffbf722fd0c)
0x00007ffbf722fcec:   e9 10 fe ff ff cc cc cc cc cc cc cc cc cc cc cc
0x00007ffbf722fcfc:   cc cc cc cc ff 25 00 00 00 00 90 69 01 80 01 00
0x00007ffbf722fd0c:   00 00 5c 24 20 55 56 57 41 54 41 55 41 56 41 57
0x00007ffbf722fd1c:   48 8d 6c 24 c0 48 81 ec 40 01 00 00 48 8b 05 a9 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x000000002055df60 is pointing into the stack for thread: 0x000000001fb06800
RCX=0x0000000020779a60 is an unknown value
RDX=0x000000002055e770 is pointing into the stack for thread: 0x000000001fb06800
RSP=0x000000002055deb8 is pointing into the stack for thread: 0x000000001fb06800
RBP=0x000000002055e250 is pointing into the stack for thread: 0x000000001fb06800
RSI=0x0000000000000001 is an unknown value
RDI=0x0000000020771da0 is an unknown value
R8 =0x0000000000000000 is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x000000002077a87c is an unknown value
R11=0x0000000000000246 is an unknown value
R12=0x0000000000000000 is an unknown value
R13=0x000000002055e770 is pointing into the stack for thread: 0x000000001fb06800
R14=0x0000000000000000 is an unknown value
R15=0x0000000000000000 is an unknown value

Stack: [0x0000000020460000,0x0000000020560000],  sp=0x000000002055deb8,  free space=1015k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [d3d9.dll+0xfd0c]
C  [d3d9.dll+0x1167f]
C  [d3d9.dll+0x276a6]
C  [d3d9.dll+0x2cb68]
C  [d3d9.dll+0x2a81e]
C  [awt.dll+0x19e3d]
C  [awt.dll+0x19f9b]
C  [awt.dll+0x1a94f]
C  [awt.dll+0x1e505]
C  [awt.dll+0x1b619]
C  0x0000000002ea7f74

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.java2d.d3d.D3DGraphicsDevice.getDeviceCapsNative(I)I+0
j  sun.java2d.d3d.D3DGraphicsDevice.access$000(I)I+1
j  sun.java2d.d3d.D3DGraphicsDevice$1.run()V+8
v  ~StubRoutines::call_stub
j  sun.awt.windows.WToolkit.eventLoop()V+0
j  sun.awt.windows.WToolkit.run()V+58
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x0000000002d90800 JavaThread "DestroyJavaVM" [_thread_blocked, id=14856, stack(0x0000000002c90000,0x0000000002d90000)]
  0x000000001fb16000 JavaThread "AWT-EventQueue-0" [_thread_in_native, id=14952, stack(0x00000000216f0000,0x00000000217f0000)]
=>0x000000001fb06800 JavaThread "AWT-Windows" daemon [_thread_in_native, id=6068, stack(0x0000000020460000,0x0000000020560000)]
  0x000000001fb06000 JavaThread "AWT-Shutdown" [_thread_blocked, id=6416, stack(0x0000000020360000,0x0000000020460000)]
  0x000000001fb05800 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=11940, stack(0x0000000020260000,0x0000000020360000)]
  0x000000001e937000 JavaThread "Service Thread" daemon [_thread_blocked, id=14472, stack(0x000000001f460000,0x000000001f560000)]
  0x000000001e8a5800 JavaThread "C1 CompilerThread3" daemon [_thread_blocked, id=14752, stack(0x000000001f360000,0x000000001f460000)]
  0x000000001e89e800 JavaThread "C2 CompilerThread2" daemon [_thread_blocked, id=14568, stack(0x000000001f260000,0x000000001f360000)]
  0x000000001e89c000 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=14580, stack(0x000000001f160000,0x000000001f260000)]
  0x000000001e898800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=14736, stack(0x000000001f060000,0x000000001f160000)]
  0x000000001e897000 JavaThread "Attach Listener" daemon [_thread_blocked, id=14740, stack(0x000000001ef60000,0x000000001f060000)]
  0x000000001e896000 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=14748, stack(0x000000001ee60000,0x000000001ef60000)]
  0x0000000002e89800 JavaThread "Finalizer" daemon [_thread_blocked, id=14516, stack(0x000000001ec70000,0x000000001ed70000)]
  0x000000001c98d000 JavaThread "Reference Handler" daemon [_thread_blocked, id=14900, stack(0x000000001e770000,0x000000001e870000)]

Other Threads:
  0x000000001c989800 VMThread [stack: 0x000000001e670000,0x000000001e770000] [id=14912]
  0x000000001e96e800 WatcherThread [stack: 0x000000001f560000,0x000000001f660000] [id=11320]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 76288K, used 11799K [0x000000076af00000, 0x0000000770400000, 0x00000007c0000000)
  eden space 65536K, 18% used [0x000000076af00000,0x000000076ba85e98,0x000000076ef00000)
  from space 10752K, 0% used [0x000000076f980000,0x000000076f980000,0x0000000770400000)
  to   space 10752K, 0% used [0x000000076ef00000,0x000000076ef00000,0x000000076f980000)
 ParOldGen       total 175104K, used 0K [0x00000006c0c00000, 0x00000006cb700000, 0x000000076af00000)
  object space 175104K, 0% used [0x00000006c0c00000,0x00000006c0c00000,0x00000006cb700000)
 Metaspace       used 10849K, capacity 11052K, committed 11264K, reserved 1058816K
  class space    used 1454K, capacity 1528K, committed 1536K, reserved 1048576K

Card table byte_map: [0x0000000012250000,0x0000000012a50000] byte_map_base: 0x000000000ec4a000

Marking Bits: (ParMarkBitMap*) 0x000000005a74b6d0
 Begin Bits: [0x00000000137b0000, 0x0000000017780000)
 End Bits:   [0x0000000017780000, 0x000000001b750000)

Polling page: 0x0000000002bb0000

CodeCache: size=245760Kb used=2204Kb max_used=2215Kb free=243555Kb
 bounds [0x0000000002e90000, 0x0000000003100000, 0x0000000011e90000]
 total_blobs=975 nmethods=510 adapters=378
 compilation: enabled

Compilation events (10 events):
Event: 0.448 Thread 0x000000001e8a5800 nmethod 507 0x00000000030a8d10 code [0x00000000030a8e60, 0x00000000030a8f70]
Event: 0.448 Thread 0x000000001e8a5800  508       1       javax.swing.text.GapVector::getGapStart (5 bytes)
Event: 0.448 Thread 0x000000001e8a5800 nmethod 508 0x00000000030a8a50 code [0x00000000030a8ba0, 0x00000000030a8cb0]
Event: 0.448 Thread 0x000000001e8a5800  505       3       java.util.Arrays::copyOf (46 bytes)
Event: 0.448 Thread 0x000000001e8a5800 nmethod 505 0x00000000030b9210 code [0x00000000030b93c0, 0x00000000030b9a68]
Event: 0.448 Thread 0x000000001e8a5800  509       1       javax.swing.text.GapVector::getArray (5 bytes)
Event: 0.448 Thread 0x000000001e8a5800 nmethod 509 0x00000000030a7290 code [0x00000000030a73e0, 0x00000000030a74f0]
Event: 0.448 Thread 0x000000001e89c000 nmethod 506 0x00000000030b9c50 code [0x00000000030b9da0, 0x00000000030ba1d8]
Event: 0.683 Thread 0x000000001e8a5800  510       3       java.util.HashMap::<init> (11 bytes)
Event: 0.683 Thread 0x000000001e8a5800 nmethod 510 0x00000000030a8610 code [0x00000000030a8780, 0x00000000030a8990]

GC Heap History (0 events):
No events

Deoptimization events (1 events):
Event: 0.443 Thread 0x000000001fb16000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x000000000305d23c method=java.lang.String.<init>([CII)V @ 18

Internal exceptions (10 events):
Event: 0.022 Thread 0x0000000002d90800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x000000076af07ca8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\
Event: 0.022 Thread 0x0000000002d90800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x000000076af07f90) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims
Event: 0.076 Thread 0x0000000002d90800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076afa8f70) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.076 Thread 0x0000000002d90800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076afa9180) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.077 Thread 0x0000000002d90800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076afacdf0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.077 Thread 0x0000000002d90800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076afad000) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.079 Thread 0x0000000002d90800 Exception <a 'java/io/FileNotFoundException'> (0x000000076afaf458) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.101 Thread 0x0000000002d90800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x000000076b1c55b8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
Event: 0.102 Thread 0x0000000002d90800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x000000076b1d2988) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\methodHandles.cpp, line 1146]
Event: 0.143 Thread 0x0000000002d90800 Exception <a 'java/io/FileNotFoundException'> (0x000000076b2841e8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u121\8372\hotspot\src\share\vm\prims\jni.cpp, line 709]

Events (10 events):
Event: 0.683 loading class sun/java2d/pipe/RenderQueue done
Event: 0.683 loading class sun/java2d/d3d/D3DRenderQueue done
Event: 0.683 loading class sun/java2d/pipe/RenderBuffer
Event: 0.683 loading class sun/java2d/pipe/RenderBuffer done
Event: 0.683 loading class sun/java2d/d3d/D3DRenderQueue$1
Event: 0.683 loading class sun/java2d/d3d/D3DRenderQueue$1 done
Event: 0.683 loading class sun/java2d/d3d/D3DGraphicsDevice$1Result
Event: 0.683 loading class sun/java2d/d3d/D3DGraphicsDevice$1Result done
Event: 0.683 loading class sun/java2d/d3d/D3DGraphicsDevice$1
Event: 0.683 loading class sun/java2d/d3d/D3DGraphicsDevice$1 done

Dynamic libraries:
0x00007ff65f930000 - 0x00007ff65f967000 	C:\Program Files\Java\jre1.8.0_121\bin\javaw.exe
0x00007ffc2e8e0000 - 0x00007ffc2eabb000 	C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffc2e140000 - 0x00007ffc2e1ee000 	C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffc2b2b0000 - 0x00007ffc2b4f9000 	C:\WINDOWS\System32\KERNELBASE.dll
0x00007ffc2e7d0000 - 0x00007ffc2e871000 	C:\WINDOWS\System32\ADVAPI32.dll
0x00007ffc2c560000 - 0x00007ffc2c5fd000 	C:\WINDOWS\System32\msvcrt.dll
0x00007ffc2be40000 - 0x00007ffc2be99000 	C:\WINDOWS\System32\sechost.dll
0x00007ffc2c9c0000 - 0x00007ffc2cae5000 	C:\WINDOWS\System32\RPCRT4.dll
0x00007ffc2e360000 - 0x00007ffc2e4aa000 	C:\WINDOWS\System32\USER32.dll
0x00007ffc2bc70000 - 0x00007ffc2bc8e000 	C:\WINDOWS\System32\win32u.dll
0x00007ffc2e510000 - 0x00007ffc2e537000 	C:\WINDOWS\System32\GDI32.dll
0x00007ffc2b120000 - 0x00007ffc2b2a8000 	C:\WINDOWS\System32\gdi32full.dll
0x00007ffc2ae50000 - 0x00007ffc2aeea000 	C:\WINDOWS\System32\msvcp_win.dll
0x00007ffc2bc90000 - 0x00007ffc2bd86000 	C:\WINDOWS\System32\ucrtbase.dll
0x00007ffc1cce0000 - 0x00007ffc1cf47000 	C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.15063.0_none_108e4f62dfe5d999\COMCTL32.dll
0x00007ffc2c6c0000 - 0x00007ffc2c9b9000 	C:\WINDOWS\System32\combase.dll
0x00007ffc2bc00000 - 0x00007ffc2bc6a000 	C:\WINDOWS\System32\bcryptPrimitives.dll
0x00007ffc2e550000 - 0x00007ffc2e57d000 	C:\WINDOWS\System32\IMM32.DLL
0x000000005a7d0000 - 0x000000005a8a2000 	C:\Program Files\Java\jre1.8.0_121\bin\msvcr100.dll
0x0000000059f30000 - 0x000000005a7cb000 	C:\Program Files\Java\jre1.8.0_121\bin\server\jvm.dll
0x00007ffc2e540000 - 0x00007ffc2e548000 	C:\WINDOWS\System32\PSAPI.DLL
0x00007ffc248d0000 - 0x00007ffc248da000 	C:\WINDOWS\SYSTEM32\VERSION.dll
0x00007ffc168f0000 - 0x00007ffc168f9000 	C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x00007ffc29100000 - 0x00007ffc29123000 	C:\WINDOWS\SYSTEM32\WINMM.dll
0x00007ffc2c4f0000 - 0x00007ffc2c55c000 	C:\WINDOWS\System32\WS2_32.dll
0x00007ffc290d0000 - 0x00007ffc290fb000 	C:\WINDOWS\SYSTEM32\WINMMBASE.dll
0x00007ffc2ae00000 - 0x00007ffc2ae49000 	C:\WINDOWS\System32\cfgmgr32.dll
0x0000000059f20000 - 0x0000000059f2f000 	C:\Program Files\Java\jre1.8.0_121\bin\verify.dll
0x0000000059ef0000 - 0x0000000059f19000 	C:\Program Files\Java\jre1.8.0_121\bin\java.dll
0x0000000059ed0000 - 0x0000000059ee6000 	C:\Program Files\Java\jre1.8.0_121\bin\zip.dll
0x00007ffc2cb50000 - 0x00007ffc2df87000 	C:\WINDOWS\System32\SHELL32.dll
0x00007ffc2c610000 - 0x00007ffc2c6ba000 	C:\WINDOWS\System32\shcore.dll
0x00007ffc2b500000 - 0x00007ffc2bbf2000 	C:\WINDOWS\System32\windows.storage.dll
0x00007ffc2e880000 - 0x00007ffc2e8d1000 	C:\WINDOWS\System32\shlwapi.dll
0x00007ffc2ade0000 - 0x00007ffc2adf1000 	C:\WINDOWS\System32\kernel.appcore.dll
0x00007ffc2ad70000 - 0x00007ffc2adbc000 	C:\WINDOWS\System32\powrprof.dll
0x00007ffc2ad50000 - 0x00007ffc2ad65000 	C:\WINDOWS\System32\profapi.dll
0x0000000059d30000 - 0x0000000059ec8000 	C:\Program Files\Java\jre1.8.0_121\bin\awt.dll
0x00007ffc2e710000 - 0x00007ffc2e7d0000 	C:\WINDOWS\System32\OLEAUT32.dll
0x00007ffc29370000 - 0x00007ffc293ee000 	C:\WINDOWS\SYSTEM32\apphelp.dll
0x00007ffc29570000 - 0x00007ffc29605000 	C:\WINDOWS\system32\uxtheme.dll
0x00007ffc2c380000 - 0x00007ffc2c4e6000 	C:\WINDOWS\System32\MSCTF.dll
0x0000000180000000 - 0x000000018006c000 	K:\Rivatuner\RivaTuner Statistics Server\RTSSHooks64.dll
0x000000005a980000 - 0x000000005aa23000 	C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9279_none_08e667efa83ba076\MSVCR90.dll
0x00007ffc27d10000 - 0x00007ffc27d3a000 	C:\WINDOWS\system32\dwmapi.dll
0x00007ffc2e210000 - 0x00007ffc2e355000 	C:\WINDOWS\System32\ole32.dll
0x0000000059ce0000 - 0x0000000059d27000 	C:\Program Files\Java\jre1.8.0_121\bin\fontmanager.dll
0x0000000059cc0000 - 0x0000000059cda000 	C:\Program Files\Java\jre1.8.0_121\bin\net.dll
0x00007ffc2a660000 - 0x00007ffc2a6bc000 	C:\WINDOWS\system32\mswsock.dll
0x0000000059ca0000 - 0x0000000059cb1000 	C:\Program Files\Java\jre1.8.0_121\bin\nio.dll
0x00007ffc2a800000 - 0x00007ffc2a817000 	C:\WINDOWS\SYSTEM32\CRYPTSP.dll
0x00007ffc2a220000 - 0x00007ffc2a254000 	C:\WINDOWS\system32\rsaenh.dll
0x00007ffc2a910000 - 0x00007ffc2a935000 	C:\WINDOWS\SYSTEM32\bcrypt.dll
0x00007ffc2ac80000 - 0x00007ffc2aca9000 	C:\WINDOWS\SYSTEM32\USERENV.dll
0x00007ffc2a820000 - 0x00007ffc2a82b000 	C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
0x00007ffc2a400000 - 0x00007ffc2a437000 	C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
0x00007ffc2e130000 - 0x00007ffc2e138000 	C:\WINDOWS\System32\NSI.dll
0x00007ffc26620000 - 0x00007ffc26636000 	C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
0x00007ffc26550000 - 0x00007ffc2656a000 	C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
0x00007ffc26370000 - 0x00007ffc26491000 	C:\WINDOWS\system32\opengl32.dll
0x00007ffc27170000 - 0x00007ffc2719c000 	C:\WINDOWS\SYSTEM32\GLU32.dll
0x00007ffbf7220000 - 0x00007ffbf73a9000 	C:\WINDOWS\system32\d3d9.dll
0x00007ffc22920000 - 0x00007ffc229ff000 	C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_a2b0acab06663645\nvldumdx.dll
0x00007ffc2af50000 - 0x00007ffc2b119000 	C:\WINDOWS\System32\crypt32.dll
0x00007ffc2adc0000 - 0x00007ffc2add1000 	C:\WINDOWS\System32\MSASN1.dll
0x00007ffc2aef0000 - 0x00007ffc2af46000 	C:\WINDOWS\System32\WINTRUST.DLL
0x00007ffc2e1f0000 - 0x00007ffc2e20d000 	C:\WINDOWS\System32\imagehlp.dll
0x00007ffbe4960000 - 0x00007ffbe5975000 	C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_a2b0acab06663645\nvd3dumx.dll
0x00007ffc1d440000 - 0x00007ffc1d615000 	C:\WINDOWS\system32\nvspcap64.dll
0x00007ffc2bf40000 - 0x00007ffc2c37b000 	C:\WINDOWS\System32\SETUPAPI.dll
0x00007ffc22c20000 - 0x00007ffc22cf7000 	C:\WINDOWS\SYSTEM32\WINHTTP.dll
0x00007ffc279b0000 - 0x00007ffc279c3000 	C:\WINDOWS\SYSTEM32\WTSAPI32.dll
0x00007ffc1df10000 - 0x00007ffc1e331000 	C:\WINDOWS\system32\nvapi64.dll
0x00007ffc29bc0000 - 0x00007ffc29c64000 	C:\WINDOWS\SYSTEM32\dxgi.dll
0x00007ffc1d620000 - 0x00007ffc1d709000 	C:\Program Files (x86)\NVIDIA Corporation\3D Vision\nvSCPAPI64.dll
0x00007ffc19680000 - 0x00007ffc19829000 	C:\WINDOWS\SYSTEM32\dbghelp.dll

VM Arguments:
java_command: D:\Downloads\vivecraft-1.10.2-jrbudda-10-final-installer (1).exe
java_class_path (initial): D:\Downloads\vivecraft-1.10.2-jrbudda-10-final-installer (1).exe
Launcher Type: SUN_STANDARD

Environment Variables:
JAVA_HOME=C:\Program Files\Java\jdk1.6.0_38
PATH=C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;D:\Skype\Phone\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\;C:\Program Files\Java\jdk1.6.0_38\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Users\Michelle\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Michelle\AppData\Local\Programs\Python\Python36-32\;C:\Users\Michelle\AppData\Local\Programs\Python\Launcher\;C:\Users\Michelle\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Java\jre1.8.0_121\bin
USERNAME=Jonathan
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 15063 (10.0.15063.296)

CPU:total 8 (4 cores per cpu, 2 threads per core) family 6 model 94 stepping 3, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, rtm, 3dnowpref, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, adx

Memory: 4k page, physical 16727500k(13143384k free), swap 19348940k(15064884k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.121-b13) for windows-amd64 JRE (1.8.0_121-b13), built on Dec 12 2016 18:21:36 by "java_re" with MS VC++ 10.0 (VS2010)

time: Fri Jun 16 12:28:27 2017
elapsed time: 0 seconds (0d 0h 0m 0s)

**Comment by jrbudda** [comment]
you seem to have this bug, which can be fixed by uninstalling rivatuner. https://bugs.openjdk.java.net/browse/JDK-8178537

**Comment by jrbudda** [comment]
Also there appears to be a rivatuner update that fixes this.

**Comment by IAMCHIDDYBANG** [comment]
Oh thank you loads! Much appreciated! Love the mod btw 😀
