### ISSUE TITLE
Losing items on death [forge]

### ISSUE THREAD

**Issue by Kerrindor** [jrbudda/Vivecraft_110#106]
Minecraft version: 1.10.2
Headset: Oculus rift

No items are dropping on death with forge installed. Tried removing minecraft and reinstalling, same issue. No other mods are installed. 

Without forge and with vivecraft: the items drop immediately on death, they leave my inventory and I can see them on the floor while on the respawn menu. As normal.

With forge and with vivecraft: the items remain in my inventory, I can see them in my hand. They are then removed when I click respawn and do not drop.

With forge and without vivecraft: behaves as normal.

Having a great time just playing and cheating my lost items back in if I die. This mod is fantastic!

**Comment by Techjar** [comment]
I can't see how this would happen, seeing as the code didn't change. Perhaps you have a mod causing this.

**Comment by Techjar** [comment]
I have confirmed that this is in fact a bug. We will look into it.

**Comment by Kerrindor** [comment]
Cool, thank you. Let me know if I can give you any more information that would help!

**Comment by jrbudda** [comment]
This should be fixed in all versions now.

**Comment by Kerrindor** [comment]
I've tested and can confirm it's fixed on this version. Thanks again!
