### ISSUE TITLE
Harvest Festival crashes

### ISSUE THREAD

**Issue by Raizerker** [jrbudda/Vivecraft_110#107]
Minecraft crashes when running Harvest Festival on Vivecraft 1.10.2.

Fails to tessellate block model.

Crash report:
[crash-2017-08-24_12.16.34-client.txt](https://github.com/jrbudda/Vivecraft_110/files/1254734/crash-2017-08-24_12.16.34-client.txt)

**Comment by jrbudda** [comment]
Try 12r7 that I just uploaded

**Comment by Raizerker** [comment]
Same error with 12r7.

[crash-2017-08-27_22.30.30-client.txt](https://github.com/jrbudda/Vivecraft_110/files/1254947/crash-2017-08-27_22.30.30-client.txt)

**Comment by Techjar** [comment]
I've re-uploaded the 12r7 build, download it again and see if it works now.

**Comment by jrbudda** [comment]
hold plz. under investigation.

**Comment by Techjar** [comment]
Re-re-uploaded 12r7, so make sure you've downloaded it again.

**Comment by Raizerker** [comment]
You guys are great! Thanks!
