### ISSUE TITLE
BetterQuesting does not show gui properly

### ISSUE THREAD

**Issue by Kuktar** [jrbudda/Vivecraft_110#108]
So a really big part of the continuum modpack from team FTB is the questing aspect of progression. Without the questbook it is possible to continue but with all the expert mode recipes it will be nearly impossible to do it efficiently. 

The big issue is that the quest gui does not show up properly i am attaching some screenshots to show an example.

https://imgur.com/a/8N8Hu55

there is a album with pictures that should help explain my issue. Thank you.

**Comment by Techjar** [comment]
Haha what the fuck, that is some seriously messed up rendering. I don't even know where to start to debug this.

**Comment by Kuktar** [comment]
Ya i am not sure either. i did mess with the mods internal settings. the defualt setting for the gui is set at -1 wich meens fullscreen.

I tried 10. 50, 200, 400

on 400 it takes up half the screen and more of the texts shows up but its still unusable

**Comment by Techjar** [comment]
For the record, it's not supposed to have borders of grass, stone and bedrock, right?

**Comment by Kuktar** [comment]
my settings are grass theme. the ones i pulled from the interwebs is using a diffrent theme

**Comment by Techjar** [comment]
Oh ok, so it's just the screwed up box clipping.

**Comment by Kuktar** [comment]
https://imgur.com/a/scALe2m

there is what it lookse like with menue background turned on. the same i believe.

**Comment by Kuktar** [comment]
not sure why i opened this on the 110 issue tracker. will reopen on 112
