### ISSUE TITLE
Lots of Crashes when moving (Lower end PC)

### ISSUE THREAD

**Issue by FinsGraphics** [jrbudda/Vivecraft_110#12]
Didn't have any issues with the 1.7.10 version of vivecraft on my lower end Alienware PC, but the 1.10 version seems to crash whenever interacting with doors, teleporting too far, various things, game will only be playable for a few min before something seems to cause it to crash. (Also I tried with and without a resourcepack and ran into the same issue)

Details:
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 20/07/16 3:52 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at ali.c(SourceFile:242)
	at ali.b(SourceFile:89)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.canStand(OpenVRPlayer.java:817)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.checkAndSetTeleportDestination(OpenVRPlayer.java:750)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportArc(OpenVRPlayer.java:636)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportDestinations(OpenVRPlayer.java:674)
	at bnz.getPointedBlock(EntityRenderer.java:3488)
	at bnz.b(EntityRenderer.java:1545)
	at bnz.updateCameraAndRender(EntityRenderer.java:1321)
	at bcx.renderSingleView(Minecraft.java:4866)
	at bcx.av(Minecraft.java:1501)
	at bcx.a(Minecraft.java:652)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at ali.c(SourceFile:242)
	at ali.b(SourceFile:89)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.canStand(OpenVRPlayer.java:817)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.checkAndSetTeleportDestination(OpenVRPlayer.java:750)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportArc(OpenVRPlayer.java:636)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportDestinations(OpenVRPlayer.java:674)
	at bnz.getPointedBlock(EntityRenderer.java:3488)
	at bnz.b(EntityRenderer.java:1545)
	at bnz.updateCameraAndRender(EntityRenderer.java:1321)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bnn['FinsGraphics'/92, l='MpServer', x=-56.28, y=76.14, z=-33.42]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (144,64,256), Chunk: (at 0,4,0 in 9,16; contains blocks 144,0,256 to 159,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 34557510 game time, 24976 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 69 total; [yb['Painting'/128, l='MpServer', x=-39.50, y=75.50, z=-2.03], bnn['FinsGraphics'/92, l='MpServer', x=-56.28, y=76.14, z=-33.42], yb['Painting'/93, l='MpServer', x=-55.97, y=77.50, z=-32.50], yb['Painting'/94, l='MpServer', x=-57.97, y=77.50, z=-32.50], yb['Painting'/95, l='MpServer', x=-53.03, y=77.00, z=-34.00], yb['Painting'/96, l='MpServer', x=-55.50, y=76.00, z=-35.97], yb['Painting'/97, l='MpServer', x=-48.03, y=76.50, z=-40.50], yb['Painting'/98, l='MpServer', x=-57.97, y=76.50, z=-45.50], yb['Painting'/99, l='MpServer', x=-55.97, y=77.50, z=-33.50], yb['Painting'/100, l='MpServer', x=-55.00, y=78.50, z=-33.03], yb['Painting'/101, l='MpServer', x=-48.03, y=76.50, z=-41.50], yb['Painting'/102, l='MpServer', x=-57.97, y=77.50, z=-34.00], yb['Painting'/106, l='MpServer', x=-57.97, y=77.50, z=-31.50], yb['Painting'/107, l='MpServer', x=-53.03, y=77.00, z=-32.00], yb['Painting'/108, l='MpServer', x=-57.03, y=76.00, z=-24.50], yb['Painting'/109, l='MpServer', x=-55.97, y=77.50, z=-31.50], yb['Painting'/110, l='MpServer', x=-59.97, y=76.50, z=-32.00], yb['Painting'/111, l='MpServer', x=-48.03, y=75.50, z=-16.50], yb['Painting'/112, l='MpServer', x=-58.50, y=76.00, z=-31.03], yb['Painting'/113, l='MpServer', x=-41.03, y=75.50, z=-16.50], yb['Painting'/114, l='MpServer', x=-39.03, y=76.00, z=-25.50], yb['Painting'/116, l='MpServer', x=-38.03, y=75.50, z=-5.50], yb['Painting'/117, l='MpServer', x=-38.50, y=75.50, z=-9.97], yb['Painting'/118, l='MpServer', x=-37.00, y=75.00, z=-14.97], yb['Painting'/119, l='MpServer', x=-46.03, y=74.50, z=-9.50], yb['Painting'/120, l='MpServer', x=-39.50, y=75.50, z=-9.97], yb['Painting'/121, l='MpServer', x=-40.03, y=75.50, z=-7.50], yb['Painting'/122, l='MpServer', x=-34.00, y=75.50, z=-9.97], yb['Painting'/123, l='MpServer', x=-39.00, y=75.00, z=-12.03], yb['Painting'/124, l='MpServer', x=-45.03, y=75.50, z=-10.50], yb['Painting'/125, l='MpServer', x=-35.00, y=75.00, z=-14.97], yb['Painting'/126, l='MpServer', x=-46.00, y=75.00, z=-5.03], yb['Painting'/127, l='MpServer', x=-40.50, y=75.50, z=-3.03], yb['Painting'/128, l='MpServer', x=-39.50, y=75.50, z=-2.03], yb['Painting'/93, l='MpServer', x=-55.97, y=77.50, z=-32.50], yb['Painting'/94, l='MpServer', x=-57.97, y=77.50, z=-32.50], yb['Painting'/95, l='MpServer', x=-53.03, y=77.00, z=-34.00], yb['Painting'/96, l='MpServer', x=-55.50, y=76.00, z=-35.97], yb['Painting'/97, l='MpServer', x=-48.03, y=76.50, z=-40.50], yb['Painting'/98, l='MpServer', x=-57.97, y=76.50, z=-45.50], yb['Painting'/99, l='MpServer', x=-55.97, y=77.50, z=-33.50], yb['Painting'/100, l='MpServer', x=-55.00, y=78.50, z=-33.03], yb['Painting'/101, l='MpServer', x=-48.03, y=76.50, z=-41.50], yb['Painting'/102, l='MpServer', x=-57.97, y=77.50, z=-34.00], xx['Armor Stand'/103, l='MpServer', x=-69.50, y=79.31, z=-60.50], xx['Armor Stand'/104, l='MpServer', x=-65.50, y=80.31, z=-38.50], xx['Armor Stand'/105, l='MpServer', x=-59.50, y=75.00, z=-24.50], yb['Painting'/106, l='MpServer', x=-57.97, y=77.50, z=-31.50], yb['Painting'/107, l='MpServer', x=-53.03, y=77.00, z=-32.00], yb['Painting'/108, l='MpServer', x=-57.03, y=76.00, z=-24.50], yb['Painting'/109, l='MpServer', x=-55.97, y=77.50, z=-31.50], yb['Painting'/110, l='MpServer', x=-59.97, y=76.50, z=-32.00], yb['Painting'/111, l='MpServer', x=-48.03, y=75.50, z=-16.50], yb['Painting'/112, l='MpServer', x=-58.50, y=76.00, z=-31.03], yb['Painting'/113, l='MpServer', x=-41.03, y=75.50, z=-16.50], yb['Painting'/114, l='MpServer', x=-39.03, y=76.00, z=-25.50], xx['Armor Stand'/115, l='MpServer', x=-35.50, y=79.31, z=-21.50], yb['Painting'/116, l='MpServer', x=-38.03, y=75.50, z=-5.50], yb['Painting'/117, l='MpServer', x=-38.50, y=75.50, z=-9.97], yb['Painting'/118, l='MpServer', x=-37.00, y=75.00, z=-14.97], yb['Painting'/119, l='MpServer', x=-46.03, y=74.50, z=-9.50], yb['Painting'/120, l='MpServer', x=-39.50, y=75.50, z=-9.97], yb['Painting'/121, l='MpServer', x=-40.03, y=75.50, z=-7.50], yb['Painting'/122, l='MpServer', x=-34.00, y=75.50, z=-9.97], yb['Painting'/123, l='MpServer', x=-39.00, y=75.00, z=-12.03], yb['Painting'/124, l='MpServer', x=-45.03, y=75.50, z=-10.50], yb['Painting'/125, l='MpServer', x=-35.00, y=75.00, z=-14.97], yb['Painting'/126, l='MpServer', x=-46.00, y=75.00, z=-5.03], yb['Painting'/127, l='MpServer', x=-40.50, y=75.50, z=-3.03]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at bln.a(WorldClient.java:496)
	at bcx.b(Minecraft.java:3297)
	at bcx.a(Minecraft.java:681)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 316094888 bytes (301 MB) / 446935040 bytes (426 MB) up to 2120679424 bytes (2022 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: vivecraft-1.10.2-Vivecraft-jrbudda-1
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.81, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 1.8 FurTrade edit (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 3
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 368.81
	OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by jrbudda** [comment]
grab the 1r1 update on the releases page I think this is fixed

**Comment by FinsGraphics** [comment]
Oh awesome! Just tried it out and I played for a good 10m without crashing! Lots of improvements already it looks like, Although I still ended up crashing whenever I put my teleport cursor over a door, or a fence gate, I assume maybe any openable object? game would instantly crash, here is the report: 

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 20/07/16 4:21 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at aid.E(SourceFile:231)
	at aid.o(SourceFile:676)
	at ali.c(SourceFile:242)
	at ali.b(SourceFile:89)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.canStand(OpenVRPlayer.java:817)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.checkAndSetTeleportDestination(OpenVRPlayer.java:750)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportArc(OpenVRPlayer.java:636)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportDestinations(OpenVRPlayer.java:674)
	at bnz.getPointedBlock(EntityRenderer.java:3488)
	at bnz.b(EntityRenderer.java:1545)
	at bnz.updateCameraAndRender(EntityRenderer.java:1321)
	at bcx.renderSingleView(Minecraft.java:4817)
	at bcx.av(Minecraft.java:1501)
	at bcx.a(Minecraft.java:652)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at aid.E(SourceFile:231)
	at aid.o(SourceFile:676)
	at ali.c(SourceFile:242)
	at ali.b(SourceFile:89)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.canStand(OpenVRPlayer.java:817)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.checkAndSetTeleportDestination(OpenVRPlayer.java:750)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportArc(OpenVRPlayer.java:636)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateTeleportDestinations(OpenVRPlayer.java:674)
	at bnz.getPointedBlock(EntityRenderer.java:3488)
	at bnz.b(EntityRenderer.java:1545)
	at bnz.updateCameraAndRender(EntityRenderer.java:1321)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bnn['FinsGraphics'/92, l='MpServer', x=-57.32, y=76.15, z=-45.52]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (144,64,256), Chunk: (at 0,4,0 in 9,16; contains blocks 144,0,256 to 159,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 34565098 game time, 24976 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 68 total; [bnn['FinsGraphics'/92, l='MpServer', x=-57.32, y=76.15, z=-45.52], yb['Painting'/93, l='MpServer', x=-55.97, y=77.50, z=-32.50], yb['Painting'/94, l='MpServer', x=-57.97, y=77.50, z=-32.50], yb['Painting'/95, l='MpServer', x=-53.03, y=77.00, z=-34.00], yb['Painting'/96, l='MpServer', x=-55.50, y=76.00, z=-35.97], yb['Painting'/97, l='MpServer', x=-48.03, y=76.50, z=-40.50], yb['Painting'/98, l='MpServer', x=-57.97, y=76.50, z=-45.50], yb['Painting'/99, l='MpServer', x=-55.97, y=77.50, z=-33.50], yb['Painting'/100, l='MpServer', x=-55.00, y=78.50, z=-33.03], yb['Painting'/101, l='MpServer', x=-48.03, y=76.50, z=-41.50], yb['Painting'/102, l='MpServer', x=-57.97, y=77.50, z=-34.00], yb['Painting'/106, l='MpServer', x=-57.97, y=77.50, z=-31.50], yb['Painting'/107, l='MpServer', x=-53.03, y=77.00, z=-32.00], yb['Painting'/108, l='MpServer', x=-57.03, y=76.00, z=-24.50], yb['Painting'/109, l='MpServer', x=-55.97, y=77.50, z=-31.50], yb['Painting'/110, l='MpServer', x=-59.97, y=76.50, z=-32.00], yb['Painting'/111, l='MpServer', x=-48.03, y=75.50, z=-16.50], yb['Painting'/112, l='MpServer', x=-58.50, y=76.00, z=-31.03], yb['Painting'/113, l='MpServer', x=-41.03, y=75.50, z=-16.50], yb['Painting'/114, l='MpServer', x=-39.03, y=76.00, z=-25.50], yb['Painting'/118, l='MpServer', x=-37.00, y=75.00, z=-14.97], yb['Painting'/125, l='MpServer', x=-35.00, y=75.00, z=-14.97], yb['Painting'/108, l='MpServer', x=-57.03, y=76.00, z=-24.50], yb['Painting'/114, l='MpServer', x=-39.03, y=76.00, z=-25.50], yb['Painting'/111, l='MpServer', x=-48.03, y=75.50, z=-16.50], yb['Painting'/113, l='MpServer', x=-41.03, y=75.50, z=-16.50], yb['Painting'/118, l='MpServer', x=-37.00, y=75.00, z=-14.97], yb['Painting'/125, l='MpServer', x=-35.00, y=75.00, z=-14.97], yb['Painting'/117, l='MpServer', x=-38.50, y=75.50, z=-9.97], yb['Painting'/119, l='MpServer', x=-46.03, y=74.50, z=-9.50], yb['Painting'/120, l='MpServer', x=-39.50, y=75.50, z=-9.97], yb['Painting'/122, l='MpServer', x=-34.00, y=75.50, z=-9.97], yb['Painting'/123, l='MpServer', x=-39.00, y=75.00, z=-12.03], yb['Painting'/124, l='MpServer', x=-45.03, y=75.50, z=-10.50], yb['Painting'/116, l='MpServer', x=-38.03, y=75.50, z=-5.50], yb['Painting'/121, l='MpServer', x=-40.03, y=75.50, z=-7.50], yb['Painting'/126, l='MpServer', x=-46.00, y=75.00, z=-5.03], yb['Painting'/127, l='MpServer', x=-40.50, y=75.50, z=-3.03], yb['Painting'/128, l='MpServer', x=-39.50, y=75.50, z=-2.03], yb['Painting'/111, l='MpServer', x=-48.03, y=75.50, z=-16.50], yb['Painting'/113, l='MpServer', x=-41.03, y=75.50, z=-16.50], yb['Painting'/118, l='MpServer', x=-37.00, y=75.00, z=-14.97], yb['Painting'/125, l='MpServer', x=-35.00, y=75.00, z=-14.97], yb['Painting'/93, l='MpServer', x=-55.97, y=77.50, z=-32.50], yb['Painting'/94, l='MpServer', x=-57.97, y=77.50, z=-32.50], yb['Painting'/95, l='MpServer', x=-53.03, y=77.00, z=-34.00], yb['Painting'/96, l='MpServer', x=-55.50, y=76.00, z=-35.97], yb['Painting'/97, l='MpServer', x=-48.03, y=76.50, z=-40.50], yb['Painting'/98, l='MpServer', x=-57.97, y=76.50, z=-45.50], yb['Painting'/99, l='MpServer', x=-55.97, y=77.50, z=-33.50], yb['Painting'/100, l='MpServer', x=-55.00, y=78.50, z=-33.03], yb['Painting'/101, l='MpServer', x=-48.03, y=76.50, z=-41.50], yb['Painting'/102, l='MpServer', x=-57.97, y=77.50, z=-34.00], xx['Armor Stand'/103, l='MpServer', x=-69.50, y=79.31, z=-60.50], xx['Armor Stand'/104, l='MpServer', x=-65.50, y=80.31, z=-38.50], xx['Armor Stand'/105, l='MpServer', x=-59.50, y=75.00, z=-24.50], yb['Painting'/106, l='MpServer', x=-57.97, y=77.50, z=-31.50], yb['Painting'/107, l='MpServer', x=-53.03, y=77.00, z=-32.00], yb['Painting'/108, l='MpServer', x=-57.03, y=76.00, z=-24.50], yb['Painting'/109, l='MpServer', x=-55.97, y=77.50, z=-31.50], yb['Painting'/110, l='MpServer', x=-59.97, y=76.50, z=-32.00], yb['Painting'/111, l='MpServer', x=-48.03, y=75.50, z=-16.50], yb['Painting'/112, l='MpServer', x=-58.50, y=76.00, z=-31.03], yb['Painting'/113, l='MpServer', x=-41.03, y=75.50, z=-16.50], yb['Painting'/114, l='MpServer', x=-39.03, y=76.00, z=-25.50], xx['Armor Stand'/115, l='MpServer', x=-35.50, y=79.31, z=-21.50], yb['Painting'/118, l='MpServer', x=-37.00, y=75.00, z=-14.97], yb['Painting'/125, l='MpServer', x=-35.00, y=75.00, z=-14.97]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at bln.a(WorldClient.java:496)
	at bcx.b(Minecraft.java:3299)
	at bcx.a(Minecraft.java:681)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 207780160 bytes (198 MB) / 433573888 bytes (413 MB) up to 2120679424 bytes (2022 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: vivecraft-1.10.2-Vivecraft-jrbudda-1r1
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.81, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 1.8 FurTrade edit
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 3
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 368.81
	OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by jrbudda** [comment]
how bout dis one.

[vivecraft-1.10.2-Vivecraft-jrbudda-1r11-installer.zip](https://github.com/jrbudda/Vivecraft_110/files/374812/vivecraft-1.10.2-Vivecraft-jrbudda-1r11-installer.zip)

**Comment by FinsGraphics** [comment]
nope still instantly crashes when looking at a fence with your teleporter.

**Comment by jrbudda** [comment]
hmmph

**Comment by FinsGraphics** [comment]
Seems any openable object will crash it.

**Comment by jrbudda** [comment]
are you sure you updated? I cant reproduce now

**Comment by jrbudda** [comment]
now r2 just to be extra certain.

[vivecraft-1.10.2-Vivecraft-jrbudda-1r2-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/374836/vivecraft-1.10.2-Vivecraft-jrbudda-1r2-installer.exe.zip)

**Comment by FinsGraphics** [comment]
Oh Im sorry I was testing with fence gates! Thats my bad, looks like doors work perfectly now!

**Comment by FinsGraphics** [comment]
Its only fence gates right now from what I cant tell, Chests are fine, doors are fine, furnaces are fine I think.

**Comment by jrbudda** [comment]
arg. ok. for reals this time.

**Comment by jrbudda** [comment]
for reals reals.

[vivecraft-1.10.2-Vivecraft-jrbudda-1r2-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/374843/vivecraft-1.10.2-Vivecraft-jrbudda-1r2-installer.exe.zip)

**Comment by FinsGraphics** [comment]
Sorry for the late replies, Im getting so lost in the world :O its %100 fixed, dude everything is so good! I am exploring my world and I would crash at every fence and door so it couldn't do much, now I can do anything!! Im already addicted to the bow.

Very well done, and thank you so much for all your effort and fixing this so quickly :)
