### ISSUE TITLE
Head always looking up for others in standard server.

### ISSUE THREAD

**Issue by Shadaez** [jrbudda/Vivecraft_110#13]
I'd like to add: if it's not possible to use the HMD looking position, the direction of the controller that causes movement or the aiming controller would be fine, but looking straight up kinda bothers my friends I guess. Or even straight forward.

**Comment by heggico** [comment]
Same here. I haven't seen it myself, but they told me I am looking forward when moving, but the moment I stop walking my head looks at the ceiling instantly.

**Comment by jrbudda** [comment]
ah i derped something, fix incoming

**Comment by jrbudda** [comment]
try 
[vivecraft-1.10.2-Vivecraft-jrbudda-1r3-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/376689/vivecraft-1.10.2-Vivecraft-jrbudda-1r3-installer.exe.zip)

**Comment by Shadaez** [comment]
Seems fixed. Thanks.
