### ISSUE TITLE
Left eye renders through walls in some cases.

### ISSUE THREAD

**Issue by Shadaez** [jrbudda/Vivecraft_110#14]
if window mirror is disabled, when you die the left eye begins rendering through walls for some reason. Opening the menu fixes it temporarily, turning the mirror back on fixes as well.

**Comment by jrbudda** [comment]
thanks the mirror thing should make this easy to track down

**Comment by jrbudda** [comment]
does it go away if you turn off FSAA?

**Comment by jrbudda** [comment]
should fix

[vivecraft-1.10.2-Vivecraft-jrbudda-1r3-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/376686/vivecraft-1.10.2-Vivecraft-jrbudda-1r3-installer.exe.zip)
