### ISSUE TITLE
Some menus not registering clicks

### ISSUE THREAD

**Issue by Shadaez** [jrbudda/Vivecraft_110#15]
Realms menu and VR Profile changer so far. Realms worked at least once, I have to switch to mouse to choose one.

**Comment by jrbudda** [comment]
Should all be working so long as window has focus.

[vivecraft-1.10.2-Vivecraft-jrbudda-2-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/379229/vivecraft-1.10.2-Vivecraft-jrbudda-2-installer.exe.zip)
