### ISSUE TITLE
Left Eye Darker on Main Menu

### ISSUE THREAD

**Issue by Kevman323** [jrbudda/Vivecraft_110#16]
For some reason the main menu screen is slightly darker in the left eye only. This seems to only affect the screen portion of the space. It's a little irritating to look at. Using r3.
![darker](https://cloud.githubusercontent.com/assets/20585337/17036490/817921ac-4f5a-11e6-890d-44d4b359fa99.png)

**Comment by jrbudda** [comment]
oh good, more opengl state weirdness... umm. does any of the mirror or FSAA options affect it?

**Comment by jrbudda** [comment]
nevermind i found it

**Comment by jrbudda** [comment]
[vivecraft-1.10.2-Vivecraft-jrbudda-1r3-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/376884/vivecraft-1.10.2-Vivecraft-jrbudda-1r3-installer.exe.zip)
