### ISSUE TITLE
Issue with GUI 

### ISSUE THREAD

**Issue by Maximeze** [jrbudda/Vivecraft_110#19]
Hi, and Thanks for this update :D

I have a blue rectangle that appears in GUI, like there is no transparency.

http://imgur.com/73zaajG
http://imgur.com/a/9gEE2

**Comment by jrbudda** [comment]
Yea I had this too on my non-development installation, it was fixed by doing 'reset video options'. So it's some setting somewhere, If you can figure out which one it is I can force-disable it.

**Comment by Maximeze** [comment]
Yes i just figured it out too, i'll try to find it, (me fellow minion.. ehh fan i mean) :D

**Comment by SamMackrill** [comment]
Setting the shaders to anything but OFF does this for me, also give constant frame drops on GTX1080

**Comment by jrbudda** [comment]
Should be fixed in release of v3
