### ISSUE TITLE
Swords cannot cut grass

### ISSUE THREAD

**Issue by Maximeze** [jrbudda/Vivecraft_110#22]
Cannot cut grass and flowers with swords, 

Even in creative mode, cannot interact with blocks with swords (Wood, stone, iron, golden, diamond)

Attacking enemy is working fine.

**Comment by jrbudda** [comment]
isnt that normal minecraft behavior?

**Comment by Maximeze** [comment]
Oh nvm, YES it is normal minecraft behavior, sorry i'm still familiar with old minecraft :P
