### ISSUE TITLE
Strange bucket behavior

### ISSUE THREAD

**Issue by 10dot** [jrbudda/Vivecraft_110#24]
Buckets only fill with water if my entire character model is submerged.  Likewise,  they only seem to empty if the character is enclosed (either indoors or digging a hole, placing a block overhead, pour water, dig out).

**Comment by jrbudda** [comment]
single or multiplayer? are you clicking to fill them or dipping?

**Comment by 10dot** [comment]
Single;  and I didn't know dipping was an option, so clicking (also, that's fucking neat... Will try when I get home)

**Comment by 10dot** [comment]
I tested this out with the latest r2 build last night and whatever else you fixed also seems to have solved this issue.

Thanks for the best thing happening on Vive right now :D
