### ISSUE TITLE
Teleportation location frozen?

### ISSUE THREAD

**Issue by Buronax** [jrbudda/Vivecraft_110#25]
Everything was working fine with teleportation as usual, but something happened and now the teleport only goes to one specific spot on the map (not on the screen, but the map).  I can use freestyle locomotion but it's poles are backwards (trying to go forwards goes backwards) and if I go back to teleport mode it takes me to the same spot from before.  Restarting minecraft didn't fix it.  Also, i'm not able to mine anything using the trigger (the pickaxe or item will move forward and back as usual but nothing will happen no matter how close I am to the block).

Sorry for that list.

**Comment by jrbudda** [comment]
Wow that is... super weird. Are you getting any console errors? Could you be in spectator mode?

**Comment by Buronax** [comment]
Okay, so I gave it a full system restart and now locomotion is working as normal. Perhaps it was some kind of spectator mode (not sure how to activate something like that though)? Right hand is working too.  Sorry to ask this here, but how does one USE the item in one's left hand (like a second pick axe for instance)? Is there a button to bind?

**Comment by Shadaez** [comment]
Can't use the offhand item in most cases, as with normal minecraft. the button that places blocks will use the offhand items meant to be used (shields, some other items in some cases).
