### ISSUE TITLE
SteamVR Home keeps appearing

### ISSUE THREAD

**Issue by Luciusp** [jrbudda/Vivecraft_110#26]
It seems to be about every 30 seconds to a minute, my view will fade in Minecraft to the SteamVR Home background, then about a second later, go back to Minecraft. I can still make actions within the game while this is happening. It likes to do this when I: move to quickly through the world, begin crafting, start breaking blocks after not doing so for about 30 seconds.  

Specs if applicable:
CPU: FX 8320 stock clocks
GPU: GTX 970
RAM: 8gb ballistix
Mobo: Sabertooth 990fx r2.0

**Comment by jrbudda** [comment]
likely a pause while chunk loading. There's not a lot I can do about that it's how minecraft is written.

**Comment by Luciusp** [comment]
Thanks! Ill take to optifine and see if I can make it better.
