### ISSUE TITLE
Button mapping menu not letting me scroll 

### ISSUE THREAD

**Issue by Buronax** [jrbudda/Vivecraft_110#28]
When I'm in the button mapping menu within the VR settings I'm only able to access the top half of the menu because I can't get it to scroll down. Grabbing the scroller on the left does nothing (or rather I can't grab it). Grabbing one of the options and trying to use it as an anchor to push up or down doesn't seem to work either.

**Comment by Shadaez** [comment]
i think its a bit buggy, it'll only scroll when you hold trigger and scroll the touchpad, don't know if that's intended.
