### ISSUE TITLE
HMD directed movement rotates movement opposite direction

### ISSUE THREAD

**Issue by en-carlson** [jrbudda/Vivecraft_110#29]
In HMD directed movement mode rotating the headset will make movement rotate in the opposite direction. If the player faces due north (0 degrees), moving forward will act as one would expect. If the player rotates right 45 degrees from north, pressing the forward key will now move the player 45 degrees left of north making them strafe right. Likewise, rotating 90 from north will make the player move backwards, and at 180, they will correctly move forwards again.

**Comment by jrbudda** [comment]
I didn't know anyone used that mode anymore, I guess I need to add a proper option button for it, i think its only accessible via hotkey, right? I never tested in in 1.10, thanks.
