### ISSUE TITLE
Nether is texture-less.

### ISSUE THREAD

**Issue by LordTocs** [jrbudda/Vivecraft_110#30]
Somehow the nether is completely devoid of textures.

Shaders are off. Lighting still works. Adjusting various graphics options didn't seem to change anything. 

[Twitch video of issue](https://secure.twitch.tv/lordtocs/v/79835733?t=02h00m42s)

**Comment by jrbudda** [comment]
Thanks. I never go in there. Easy fix.

**Comment by LordTocs** [comment]
Baller. Glad you found it. I tried to debug it but I couldn't get RenderDoc or gDEbugger to capture.
