### ISSUE TITLE
Using Vive, image seems to mismatched on each lens.  Both on screen and on headset

### ISSUE THREAD

**Issue by IronRico** [jrbudda/Vivecraft_110#31]
So when I boot up the newest release (1.10.2), I get to the main menu OK, but when a world loads up the image is totally off.  When I checked the desktop, the I could see that the left image was minuscule justified to the left, while the right image was seemingly rotated 90 degrees and set somewhat full screen, (to that side anyways).

I also tried turning off desktop mirror in the Steam VR settings too, yet same issue.  This happens on new and existing worlds.

I am using 980's in SLI.  I did disable SLI to see if that was the issue, but same results.

Even messed around with graphics options as well.  

Any takers?

**Comment by IronRico** [comment]
I attached a screen shot of what I seem to be getting now after trying out some more tweaks.  Not a good run.

![capturegh](https://cloud.githubusercontent.com/assets/20647008/17111145/e0f1b0dc-5265-11e6-8b74-a8ab55c6b325.JPG)

**Comment by jrbudda** [comment]
see if you can get to the reset video options menu, i'm thinking maybe AA or one of the other no-no options must be turned on.

**Comment by IronRico** [comment]
Thanks for the  suggestion jrbudda.  

I had done this earlier, however I think the issue was that reinstalled the data and never bothered to do it again thinking it was a step I already passed.  

As per the norm, the answer is easy.   Just a little user error.

Works great now.  Using the Chroma Hills pack with it and it runs sweet.

**Comment by jrbudda** [comment]
thanks, ive got a couple of those video options causing problems, will work on force-disabling them.
