### ISSUE TITLE
Issues with mining blocks without having to swing manually

### ISSUE THREAD

**Issue by delivus** [jrbudda/Vivecraft_110#32]
Hello! I love your work first off! Big fan! 
I was playing 10.2 and suddenly I couldn't mine blocks with the trigger anymore. i had to manually swing my arm to break them. Though its great for immersion, it gets a bit tedious when your strip mining lol. Weird thing is it still worked for hitting enemies/animals and grass. 

Thanks again!

**Comment by jrbudda** [comment]
Yes this has been reported and is being investigates.

**Comment by jrbudda** [comment]
duplicate of #27
