### ISSUE TITLE
Major Issue - Unplayable

### ISSUE THREAD

**Issue by xx1guardian1xx** [jrbudda/Vivecraft_110#33]
So I jump into a world, first thing I notice left eye is all buggy then the game begins to lag, frames drop from 90-50-20-10-1 real quick, main menu works fine just in game. Heres an image example
![1](https://cloud.githubusercontent.com/assets/3170050/17159646/a7c93d66-5396-11e6-8cd7-59c0f986c66f.png)

**Comment by jrbudda** [comment]
do a reset of the video options in Video Settings > Other > Reset

**Comment by jrbudda** [comment]
caused by AA options. now force disabled in v3.
