### ISSUE TITLE
Nonexistent JRE in registry

### ISSUE THREAD

**Issue by slowshutterfilms** [jrbudda/Vivecraft_110#36]
I'm trying to run the most recent installer (1.10 vr3), but when I run it a error comes up and says "The registry refers to a nonexistent Java Runtime Environment installation or the runtime is corrupted." Is there away to delete or correct the registry entry? Thanks

**Comment by jrbudda** [comment]
I have no idea, have you tried ininstalling and reinstalling java?

**Comment by slowshutterfilms** [comment]
Uninstalled java, cleaned the registry, and then reinstalled it. Works now, thanks :)
