### ISSUE TITLE
Menu does not render when not holding an item

### ISSUE THREAD

**Issue by finaltransmit** [jrbudda/Vivecraft_110#37]
Sometimes the game menu does not render correctly, the player appears transparent and all transparent blocks do not render. This does not happen when the player is holding something in either hand.

![bug](https://cloud.githubusercontent.com/assets/13271560/17278319/d065530a-575a-11e6-821f-d4e9622f9460.png)

**Comment by jrbudda** [comment]
should be fixed here.

[vivecraft-1.10.2-Vivecraft-jrbudda-4-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/395049/vivecraft-1.10.2-Vivecraft-jrbudda-4-installer.exe.zip)
