### ISSUE TITLE
Switching button profile breaks button functionality

### ISSUE THREAD

**Issue by finaltransmit** [jrbudda/Vivecraft_110#38]
Switching button profile while in game causes no buttons except the menu button to have any effect. This is not fixed until the game is restarted.

**Comment by jrbudda** [comment]
Do you mean the VR Profiles? yea those don't work see https://github.com/jrbudda/minecrift/issues/69

**Comment by finaltransmit** [comment]
For me they seem to work fine if i restart minecraft

**Comment by jrbudda** [comment]
Duplicate of https://github.com/jrbudda/minecrift/issues/69
