### ISSUE TITLE
Sky colours different between left and right eye when opening chests

### ISSUE THREAD

**Issue by ArduousWolf** [jrbudda/Vivecraft_110#39]
I mentioned this happening in the thread for issue 27 but it seemed to correct itself.
It has happened again and I finally managed to get a screenshot. The sky returns to normal once the chest is closed.

![vivecraft issue2](https://cloud.githubusercontent.com/assets/20599711/17304095/c0d58a92-581b-11e6-918d-39b2791848ff.png)

**Comment by jrbudda** [comment]
any idea what exactly is causing it? I can't reproduce it. Maybe something to do with which items are being drawn in the chest? or some specific video options you have turned on?

**Comment by jrbudda** [comment]
Also lets make sure it's not something I've already fixed.

[vivecraft-1.10.2-Vivecraft-jrbudda-4-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/394893/vivecraft-1.10.2-Vivecraft-jrbudda-4-installer.exe.zip)

**Comment by jrbudda** [comment]
still an issue?

**Comment by jrbudda** [comment]
assuming fixed
