### ISSUE TITLE
Click repeat speeds wrong

### ISSUE THREAD

**Issue by jrbudda** [jrbudda/Vivecraft_110#4]
Did not fully port over the exact click delay / speeds from 1.7.10

**Comment by Jonas-Mikkelsen** [comment]
The causes me to break two blocks instanly instead of one in creative mode

If there is a block behind the one i want to break, then that block will also be broken

**Comment by jrbudda** [comment]
left click fixed, still need to look at right click.

**Comment by jrbudda** [comment]
Think I got em.
