### ISSUE TITLE
Hotbar sticks through shield

### ISSUE THREAD

**Issue by rogueqd** [jrbudda/Vivecraft_110#43]
The inventory hotbar sticks through your shield. It's a bit immersion breaking. With all your great work so far it would be nice to improve it.  
Some suggestions..
Strap to your forearm instead of your hand
A Hotbar button that would make a floating hotbar appear in front of you while the button is held down? (so no hotbar at all unless the button is held)
Attach it to the players waist instead of their hand, so you look down to see it. (you could make it vertical and we could compare hotbar sizes)

**Comment by jrbudda** [comment]
what about wrist-lock mode?

**Comment by rogueqd** [comment]
Is that the one you had before where it sort of popped up when you went to select something? I haven't seen that in 1.10. Is there an option already that I missed?

**Comment by rogueqd** [comment]
Oh man, there's 4 options, you already have most of my suggestions. Sorry, I feel like a noob for opening the issue, lol.  
Can you make wrist lock mode the default?
Also, the hotbar shows through your arm when it's facing towards the ground. It should be hidden behind it, can that be changed?

**Comment by jrbudda** [comment]
yes that the 'hud occulusion' setting. The default isn't gonna change since people are very used to where it is.

**Comment by rogueqd** [comment]
Closed - thanks for your patience.
