### ISSUE TITLE
HUD occlusion doesn't work with shaders.

### ISSUE THREAD

**Issue by rogueqd** [jrbudda/Vivecraft_110#44]
HUD occlusion ON works properly with shaders Off.
With shaders on the HUD is always visible through your arm. (as if HUD occlusion was Off)
Using Sildurs Vibrant Shaders v1.141 Lite

**Comment by jrbudda** [comment]
I dunno if I can fix this. Drawing the HUD so shadersmod gets the correct depth for occlusion screws up the hud colors real bad.

**Comment by jrbudda** [comment]
cant fix really
