### ISSUE TITLE
Room-scale boat turning should be inverted like an actual boat

### ISSUE THREAD

**Issue by vgf89** [jrbudda/Vivecraft_110#47]
If you paddle (accelerate) on one side, you should turn the opposite way (since you're pushing that side of your boat , rather than towards your oar. Turning towards the oaring side feels very wrong and inconsistent with how watercraft work IRL.

**Comment by jrbudda** [comment]
you row backwards in a rowboat tho. you pull the oar on the right and turn to the right.

**Comment by vgf89** [comment]
I'd agree if the game cared which direction you row your hands, but it it turns the same way regardless. If you're only making a slight turn while already moving your boat IRL, you wouldn't row backwards, you'd just stop rowing on one side and keep rowing forward on the other.

The other way to think of it is kind of like a tank. If you turn on the right wheel, you're going to then left.

I think the controls should either be inverted, or the direction of rowing needs to be taken into account for turning.

**Comment by jrbudda** [comment]
The intention is you face away from the way you want to go, as in a rowboat, and pantomime rowing.
There is no paddling 'backwards' as you noted. It's on the wishlist but a ugly thing to try and detect reliably, and even uglier to present to player as there is no way to provide visual feedback..  So any motion is a paddle ahead on that side (i.e. pulling the oar handle towards you). 

It is working as intended, given the limitations.

**Comment by vgf89** [comment]
It still feels pretty weird since I'm used to usually steering right using
left and vice versa when paddle boarding.

The problem I see is that there are two perfectly valid ways to do the same
thing (steer right by rowing backwards on your right, or steer right by
rowing forwards on the left), and we're only given one of them.

Could an inverted boat steering option possibly be added? The non-inverted
steering really messes with my muscle memory.

**Comment by jrbudda** [comment]
Have you ever used a rowboat?

**Comment by vgf89** [comment]
No, but I assume even there, you could steer not just by pulling one paddle, but if you need to turn faster you'd also push the other paddle.

What I have used is a paddleboard, where I use a single paddle to control my movement.

Here's the thing though. If I'm doing a shallow turn while already moving forward, I just keep paddling forward on a single side (to prevent from losing speed). If my paddling on the left, I'll turn right. If I want to do a much sharper turn, I move the paddle to the side I want to turn and paddle backwards. The former action is much more frequent than the latter, so that's how my brain defaults to steering.

Also, how I remember boats working in minecraft on a keyboard (at least pre-1.10, I haven't tried them in vanilla since), is that you can't even turn sharply once you gain speed. This is pretty much equivalent to paddling normally on one side and just not paddling at all on the other IRL.

**Comment by jrbudda** [comment]
I already explained the lack of paddling backwards. Everything else works exactly as you described except that your expectation for which way you turn is wrong for this type of boat.

**Comment by vgf89** [comment]
If there's no "paddling backwards", how in the world would rowing on the right turn you right?

**Comment by jrbudda** [comment]
Google how a rowboat works. The oars are on a pivot and you sit backwards in the boat. Your right is the boats port side.

**Comment by vgf89** [comment]
Ok, I guess that makes sense then. Then perhaps the player should be placed backwards in the boat to start with.

**Comment by jrbudda** [comment]
That's a good idea

**Comment by jrbudda** [comment]
Hmm that would require an across the board change to all vehicles that your orientation with respect to the vehicle is fixed and the world rotates around you to accommodate. That my be massively disorienting to some people.

**Comment by vgf89** [comment]
Not sure how hacky it would be, but I'd just add 180 degrees to the headset orientation (perhaps optional) while in the boat.

**Comment by jrbudda** [comment]
The boat orients correctly when you enter it. Played with the idea of fixing the player's rotation with respect to the vehicle but had to disable the option before the release of v6 as it was causing technical issues. Will look into re-implementing later as it did have promise, expeically for minecarts.
