### ISSUE TITLE
Hud offsets require game restart

### ISSUE THREAD

**Issue by jrbudda** [jrbudda/Vivecraft_110#51]
from reddit 

The HUD menu settings (Specifically the size, horizontal, and vertical positions) only updates when you restart the game and sometimes it will set at a lower setting then what is set. No idea how to reproduce this one, sorry.

**Comment by jrbudda** [comment]
this person is crazy, those settings dont do anything at all.

**Comment by jrbudda** [comment]
Removed non-functional settings.

**Comment by MoliskScout** [comment]
Oh great I spent about half a hour trying to figure out what they do.
