### ISSUE TITLE
Going into Languages menu crashes game

### ISSUE THREAD

**Issue by Anahkiasen** [jrbudda/Vivecraft_110#52]
Not sure if it's an issue with my computer or the mod but when I go into the Languages menu in the options the game stops rendering in VR. The mirror display is still there on the desktop but is refreshed something like every 10/15s, so I'm guessing it's having an issue rendering the list maybe?

Controls still seem to work cause I put the game in russian by mistake and had to edit my settings manually to get it back :p

**Comment by jrbudda** [comment]
hmm yea it seems to get stuck in some kind of loading loop when you choose a language, but only sometimes..

**Comment by jrbudda** [comment]
I think fixed
