### ISSUE TITLE
Feature request: updated crafting, or maybe as an option.

### ISSUE THREAD

**Issue by hitchikersguide** [jrbudda/Vivecraft_110#53]
This one is sort of a moonshot and would take some real consideration on approach. If you so choose to accept this mission:

Physical crafting. Forget the formulaic grid crafting. It's bold, and possibly damn near impossible on the platform.....still here?

Maybe a way using your two hands can build all the items? Or even just start with items built on 2x2 grid? If not possible, what about gesture crafting?

**Comment by Platoonsgt1** [comment]
You could keep it a little simpler, and relevant to Minecraft:
Physically place the items onto the crafting table! Actually, I think there was a mod that worked like that at some point, it created a temporary blue crafting grid on the ground...
