### ISSUE TITLE
Armswing locomotion catches on shallow water/climbable blocks 

### ISSUE THREAD

**Issue by thesambassador** [jrbudda/Vivecraft_110#54]
When moving with new locomotion options, I frequently get "caught" on the edges of climbable blocks.  It seems that when a climbable block is nearby, it assumes that you want to switch to "climb mode" and then the normal armswing locomotion doesn't move you anymore.  Try running through a jungle biome and this will become obvious.

The same problem exists when touching water (usually from a waterfall or something).  It seems to switch to "swimming controls" as soon as you collide with any water, even if your "feet" are touching the ground through the water.

**Comment by jrbudda** [comment]
I believe both of those annoyance have been fixed already. Try this out and let me know!.

[vivecraft-1.10.2-Vivecraft-jrbudda-6pre-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/426036/vivecraft-1.10.2-Vivecraft-jrbudda-6pre-installer.exe.zip)

**Comment by jrbudda** [comment]
Shouldbe fixed in 6
