### ISSUE TITLE
Poor GPU Utilization

### ISSUE THREAD

**Issue by Leo11504** [jrbudda/Vivecraft_110#55]
So I noticed an issue with GPU Utilization when playing with shaders recently. It appears that Vivecraft will not use more then 50% of the GPU power given to it, this means that it will instead default to 45 and reproject instead of pushing a higher frame rate.

I tested this with various levels of chunk view distance, reprojection on or off (through SteamVR settings) and testing using both Kuda and Seus shaders at low and Ultra quality. 

Regular Minecraft with optifine and shaders will use 99-100% GPU usage and (shader settings dependent) 60-200+FPS but when switching to Vivecraft the GPU utilization refuses to push past 50%.

I've also tested this by going into a shaderless version of Vivecraft and maxed out the chunk view distance to 32 and supersampling to 4.0 and while it manged a 45FPS reprojected my GPU Utilization will not pass 50%

I noticed the same performance issues when switching back to older Nvidia drivers, older versions of Vivecraft or swapping out to my GTX 970 GPU.

I wanted to let you know my finding and see if there is a possible fix.

System Specs:
4770K @4.3Ghz
16GB DDR3 @ 1833Mhz
GTX 1080 FTW at default and 2Ghz on Driver 372.54
GPU performance shown using the latest MSI Afterburner.

**Comment by jrbudda** [comment]
That's the steamvr compositor blocking the rendering (only) thread waiting for the reprojection. It's less of an issue on a properly coded game but this is minecraft where the rendering is fixed-pipeline and the single-threaded to boot. I do not know of a fix short of rewriting the game.
