### ISSUE TITLE
User's height change

### ISSUE THREAD

**Issue by gladiusz** [jrbudda/Vivecraft_110#56]
HI. I'd like to know, if it's any option to change user's height in game. I'm using Riftcat Vridge and PSMoveService and in SteamVR my height is set to 1 meter. In game I can't use controllers, beacuse they are seated too low and when i hit calibrate height button it says that my height is 2,60 m. It'd be awesome, if I could change it manually in game.

**Comment by jrbudda** [comment]
You want the 'reset origin' button which can be found on the VR Settings menu as of version 6.

**Comment by Scampernoodle** [comment]
i know u not gonna reply cuz i am 4 years late but you use google cardboard and ps move?! why did i spend loads of money on a oculus rift XD
