### ISSUE TITLE
Using a bed pops up the keyboard

### ISSUE THREAD

**Issue by Anahkiasen** [jrbudda/Vivecraft_110#57]
Not sure if this is a bug or something, but using a bed is currently kind of awkward. It pops up the Steam keyboard and the actual screen gets "projected" into the world in a weird way instead of fading out the HMD's screen.

**Comment by zenmetsu** [comment]
Just stating that this has been replicated on my end.

Also, red tint while sleeping should probably be changed to a neutral grey as it leads one to suspect a low health situation.
