### ISSUE TITLE
[Request] New locomotion methods!

### ISSUE THREAD

**Issue by Mage-Enderman** [jrbudda/Vivecraft_110#58]
please add something like https://www.youtube.com/watch?v=0r4PkBYc_fk Blink mode maybe direction controlled by where the controller is pointing or maybe like your room scale walking mode

and now I list some methods that I think would work well from some games(well the name of the game not all of them have names for the method of locomotion) 
Spell Fighter(the teleportation in it)
World Rotator(https://www.youtube.com/watch?v=p0YxzgQG2-E   9:42)
WalkAbout
Snap N´Motion(https://www.youtube.com/watch?v=QxNfZh-bCN8)

**Comment by jrbudda** [comment]
The incremental teleport is interesting tho it comes with some challenges in dealing with the highly vertical nature of minecraft.

Also there's currently walkabout in the game you just have to bind it to a button. I dont think a lot of people use it as there's just too much distance to cover. the 'automatic' walkabout (world rotator) is interesting tho and might be a easy addition.

tbh that snap n motion looks terrible. lol.

**Comment by Mage-Enderman** [comment]
Awesome also since I don't have a vive yet the snap n motion just looked alright but the way he was showing it was terrible

**Comment by MoliskScout** [comment]
"Regular" trackpad movement for the ones with iron guts. I can't map all for axes for the trackpad buttons because the way they set up in 45° angle.
I suggest a "dropdown" settings for the left, right trackpads which should include a 2 axes analog movement. And also a "none". I don't use scrolling only by accident.

**Comment by wingzx3** [comment]
I think this game has a great locomotion system for walking + teleporting.  Trickster VR.
https://www.youtube.com/watch?v=W8W2fRyqBYc

If you press the touch pad you walk in the direction of the controller and the angle you point the controller modifies the run speed.  So pointing directly down you walk slowly while pointing directly in the direction you want to move makes you run.  Double tapping the touch pad will cause you to "sprint/blink" towards that direction in a fixed amount of distance.

This works really well for combat and general immersion.  This allows for precision movement as well as quick movements without having to change the speed settings in the menu.

**Comment by wingzx3** [comment]
I was able to build the 1.7.10 version of vivecraft and modify the code at the bottom of 
in MovementInputFromOptions.java
```
        IRoomscaleAdapter con = Minecraft.getMinecraft().roomScale;  
        float pitch = con.getControllerOffhandPitch_World();
        float speedModifier = (90.0F - Math.abs(pitch))/90.0F;
        this.moveForward = this.moveForward * vr.movementSpeedMultiplier * speedModifier;
        this.moveStrafe  = this.moveStrafe * vr.movementSpeedMultiplier * speedModifier;
```

This works quite well.  I wasn't able to build the 1.10.2 version to try.  I would like some help getting it to build if possible.
