### ISSUE TITLE
Failure to Launch

### ISSUE THREAD

**Issue by Slitty** [jrbudda/Vivecraft_110#59]
A few days ago I purchased and received a Vive. After a little research I found Minecrift and tried it out. Aside from some buggy controls and a lack of a few controls it worked just fine. A day or so ago I found Vivecraft which appears to be the successor to Minecrift and I was thrilled to see that it had seemed to have all the controls that Minecrift was missing. Unfortunately after installing Vivecraft I could not get it to launch. I followed all the steps (install minecraft, install forge 10.13.4.1614, install vivecraft with forge and binural audio). I press play it downloads the files it needs and then promptly crashes with the attached error log. Am I installing it incorrectly? Or is it possible that it's a fault on the side of forge? Maybe even a hardware issue?
[vivecraft-1.7.10-Vivecraft-jrbudda31r3-forge (2016-08-29).txt](https://github.com/jrbudda/Vivecraft_110/files/443323/vivecraft-1.7.10-Vivecraft-jrbudda31r3-forge.2016-08-29.txt)

**Comment by jrbudda** [comment]
have you tried it without any mods installed?

**Comment by Slitty** [comment]
Yes, I completely deleted my .minecraft folder and tried to play with a clean install.

**Comment by jrbudda** [comment]
ok can you paste a crashlog without mods?

**Comment by Slitty** [comment]
That crashlog should only have the version of optifine that comes bundled with Vivecraft

**Comment by jrbudda** [comment]
nope its got liteloader and fastcraft and a buncha other stuff

**Comment by Slitty** [comment]
oh right, I have the other one without the mods must've saved the wrong one
[vivecraft-1.7.10-Vivecraft-jrbudda31r3-forge (2016-08-29).txt](https://github.com/jrbudda/Vivecraft_110/files/443364/vivecraft-1.7.10-Vivecraft-jrbudda31r3-forge.2016-08-29.txt)

**Comment by jrbudda** [comment]
hmm i just tried a install of that version and it worked with no problem, so im not sure whats going on, i'll have to look closer at that error, there isnt any actual vivecraft code called in it, its just Forge

**Comment by jrbudda** [comment]
oh I just noticed this 
[L] Running under TLauncher 1.72 For Mc-Launcher.com
try with the minecraft launcher

**Comment by Slitty** [comment]
yep, same problem. I use the TLauncher because it has a console window unlike the regular launcher.
[fml-client-latest.txt](https://github.com/jrbudda/Vivecraft_110/files/443455/fml-client-latest.txt)

**Comment by jrbudda** [comment]
the regular minecraft launcher shows errors in the Game Output tab. Could you paste the Launcher Log tab when you start it up. I think the launcher is failing to download the minecraft jar itself

**Comment by Slitty** [comment]
Huh, well I think it may have been a firewall problem or like you suggested just a failuire to download some files because I added an exception for java and the launcher in the firewall and it just started up fine. Thanks for the help!

**Comment by jrbudda** [comment]
cool glad you got it working
