### ISSUE TITLE
Render Setup Failed ... Invalid Connect Responce (307)

### ISSUE THREAD

**Issue by zexelon** [jrbudda/Vivecraft_110#61]
I have just downloaded and installed minecraft for the first time to test out vivecraft. Minecraft runs without issues however after installing Vivecraft (tried both the 1.7 and 1.10 code path) I receive the following error Render Setup Failed Shared IPC Compositor Invalid Connect Response (307). 

I am assuming I have the latest SteamVR (just set it up for the first time yesterday). I also have no other mods installed. 

I have also attached the minecraft output, but it does not appear to have any errors. 

[minecraft output.txt](https://github.com/jrbudda/Vivecraft_110/files/454125/minecraft.output.txt)

![minecraft error](https://cloud.githubusercontent.com/assets/21991336/18234088/82778a7e-72b6-11e6-96ae-5a89fe9cc960.PNG)

**Comment by jrbudda** [comment]
This has been fixed by other by running as administrator, or making sure the pc is set to use the correct GPU all the time

**Comment by zexelon** [comment]
Sure enough it was a hardware issue. I had 2x ATI 7970 gfx cards in my system, when I took the second one out of the computer everything ran fine and the program ran with no issues until something else caused a crash. 

I am going to say it works fine now. Minecraft in Vive is mind blowing! Keep up the good work!

**Comment by DJTrickyM** [comment]
same issue, tried setting steam and vrmonitor to admin and steam kept saying its running in compatability mode which can break stuff. then steam was giving a similar error. after undoing the admin privilages, steamvr wouldnt start at all. 

after a computer reboot, at first it said something didnt work right, but after restarting steamvr it seems to be ok. 

tried minecraft just now and...its working...

GTX 970 idk what happened but its ok i guess, will report if further issues related to this occur

**Comment by DJTrickyM** [comment]
wored fine, except therees a huge graphical error with shaders :(

**Comment by MoliskScout** [comment]
I got this error too a few times. And similar ones in non steam games.
The explanation I found was that steam vr dashboard can block access of non steam games.
Starting only  "common\SteamVR\tools\bin\win32\vrmonitor.exe" then starting the non steam app solved this problem for me.
