### ISSUE TITLE
Seemingly unable to sprint

### ISSUE THREAD

**Issue by Redhotsmasher** [jrbudda/Vivecraft_110#62]
(playing in seated mode on my Rift DK1) Sprinting seems broken in Vivecraft. Double tapping forward just walks forwards, holding LCTRL (default bind for sprint, haven't changed it) doesn't seem to do anything. Switching to vanilla profile, sprinting works normally, switching back to Vivecraft, sprinting does not.

**Comment by jrbudda** [comment]
Sprinting is not much faster than walking (1.3 v 1.0 m/s). Are you sure it's not sprinting and you just can't tell because there is no FOV change?
