### ISSUE TITLE
Chat closes on 'Enter', keyboard stays open

### ISSUE THREAD

**Issue by ArmEagle** [jrbudda/Vivecraft_110#66]
Version 1.10.2

Using the '3d keyboard' when I use 'Enter' to submit typed text in chat, the chat window (with the typed text) is closed (immediately). The keyboard stays open though.

I expect to be able to keep chatting until I'm 'Done'.

**Comment by jrbudda** [comment]
That's how the minecraft chat window works, when you hit enter it goes away. The 'done' button on the steamVR keyboard does not send anything to the game so I don't know when it's clicked, would have to come up with a different way to close the chat window.

**Comment by ArmEagle** [comment]
Sometimes these free handy things (SteamVR keyboard) are great. Often one wishes they'd have more control over it. Then you could map 'Enter' to 'Enter + reopen chat'. And perhaps add another button labeled 'Enter + close'.
