### ISSUE TITLE
Failure to launch after update

### ISSUE THREAD

**Issue by john5246** [jrbudda/Vivecraft_110#67]
This used to work great during 1.7... 

I upgraded to the latest version and also updated java, had some java issues but installed 64bit and I think it's good now. Here is a pastebin of the errors without mods

http://pastebin.com/i05LZUe1

I did a clean install of minecraft, vivecraft, and even java (in the process used 64bit) and still no luck

Vivecraft: 1.10.2 
Minecraft: 1.10.2
Java: 1.8.0_101
OS: Windows 10 Pro 64bit Latest 

Any help would be great, can you steer me in the right direction to what's causing this?

**Comment by Chicachu** [comment]
I'm also on Windows 10 pro, tried installing everything from scratch and when I press play with the vivecraft profile selected it starts to download something then goes right back to showing "play" on the button and nothing happens. I never tried an earlier version, thus is my first time with vivecraft and have had no luck.

**Comment by jrbudda** [comment]
sorry pastebin expired, still an issue? maybe also check here http://www.vivecraft.org/faq/

**Comment by Chicachu** [comment]
I manually downloaded all of the libraries and it started up just fine. :) There was just something wrong with the download.  

    On Friday, December 2, 2016 8:03 AM, jrbudda <notifications@github.com> wrote:
 

 sorry pastebin expired, still an issue? maybe also check here http://www.vivecraft.org/faq/—
