### ISSUE TITLE
Run-in-place issues

### ISSUE THREAD

**Issue by Chimera245** [jrbudda/Vivecraft_110#68]
I tried the "run-in-place" movement, but if feels a little weird. I can't seem to change direction while moving. I have to stop dead, then face a new direction then start moving again.

Whether it's the controllers or the headset or both, pointing in a different direction does nothing until I stop. 

I have an iron stomach, so motion sickness never bothers me. I typically play in free movement mode, pulling the trigger to go "forward", then waving my hand around, performing acrobatic pirouettes around creepers and zombies.

(On a side note, it is SO SATISFYING to run full-tilt past a monster, and swing my sword at it as I run by...Especially in creative mode, flying around The End, picking off Ender Crystals...)

Anyway, I can't figure out how to do that in run-in-place mode. I read the pop-up that says it takes "the average direction of both controllers" to determine the movement direction, but it never seems to want to recognize anything but pointing straight forward. Am I supposed to be able to go backwards or sideways? If not, my creeper-strafing days are over...

As a lesser issue, how do I run and jump at the same time? (with run-in-place) Do I just keep wiggling my arms while I jump? I can't seem to stop myself from raising my arms up a bit in tandem when I jump. That stops the running-arm-wiggle for a moment, and slows me down or stops me... Do I just need to practice? Or am I supposed to physically jump forward in real space when I want to do something like jump a gap?

**Comment by jrbudda** [comment]
The way it's coded no, you cant run backwards with run-in-place, how would it know? For jumping yea you'll have to keep your arms moving to maintain momentum while jumping, that's just how minecraft works.

**Comment by jrbudda** [comment]
run in place has been tweaked a little, maybe its better now?
