### ISSUE TITLE
Vridge and null driver

### ISSUE THREAD

**Issue by evgen-y2k** [jrbudda/Vivecraft_110#72]
I try run vivecraft with Riftcat and with Null Driver but always I have errors and VR server falls. Was checked all versions of vivecraft and all possible versions of Java (32 and 64 bit). Same situation. Other VR games from Steam works perfectly. My systems:
#1

Win 10 64
Video: Intel IRIS 6100 
CPU: Intel Core I3 5157U
RAM: 8 Gb
#2

Win10 64
Video: Intel HD Graphics 5300
CPU: Intel Core M 5Y10C
RAM: 4Gb
#3

Win10 64
Video: Nvidia 820M
CPU: Intel Core I7 4500
RAM: 8Gb 

Errors from minecraft log:
[08:27:10] [Client thread/ERROR]: ########## GL ERROR ##########
[08:27:10] [Client thread/ERROR]: @ post 2d 
[08:27:10] [Client thread/ERROR]: 1282: Invalid operation
[08:27:10] [Client thread/ERROR]: ########## GL ERROR ##########
[08:27:10] [Client thread/ERROR]: @ post 2d 
[08:27:10] [Client thread/ERROR]: 1282: Invalid operation

**Comment by jrbudda** [comment]
I've not tried riftcat myself, have you followed all the directions here https://support.riftcat.com/hc/en-us/articles/210659549-Minecraft-How-to- ?

**Comment by evgen-y2k** [comment]
This link was my first step :( Doesn't worked for me. You can try use Null Driver for test. It is easy. Look to this link (steamvr.vrsettings file format): https://developer.valvesoftware.com/wiki/SteamVR/steamvr.vrsettings
And for example my config below:
{
    "dashboard": {
        "enableDashboard": false
    },
    "driver_null": {
        "enable": true,
        "id": "Null Driver",
        "renderHeight": 720,
        "renderWidth": 1280,
        "secondsFromVsyncToPhotons": 0.10000000149011612,
        "serialNumber": "Null 4711",
        "windowHeight": 1080,
        "windowWidth": 1920,
        "windowX": 0,
        "windowY": 0
    },
    "perfcheck": {
        "heuristicActive": false
    },
    "steamvr": {
        "allowReprojection": false,
        "forcedDriver": "null",
        "mirrorViewGeometry": "0 0 960 540",
        "startMonitorFromAppLaunch": false,
        "activateMultipleDrivers": true
    },
    "leap": {
        "gripAngleOffset_lefthand": 0,
        "gripAngleOffset_righthand": 0,
        "renderModel_lefthand": "vr_controller_vive_1_5",
        "renderModel_righthand": "vr_controller_vive_1_5"
    },
    "leap_gestures": {
        "GrabPressed": "GestureWithin:LowerFist[0.5,1.0]",
        "MenuPressed": "GestureWithin:FlatHandPalmTowards[0.5,1.0]",
        "SystemPressed": "GestureWithin:FlatHandPalmAway[0.5,1.0]",
        "TouchpadAxis[0]": "GestureAxis:ThumbPositionX[-1.0,-1.0]",
        "TouchpadAxis[1]": "GestureAxis:ThumbPositionY[-1.0,-1.0]",
        "TouchpadPressed": "GestureWithin:Thumbpress[0.5,1.0]",
        "TouchpadTouched": "GestureWithin:Thumbpress[0.0,0.5]",
        "TriggerAxis[0]": "GestureAxis:TriggerFinger[0.0,1.0]",
        "TriggerAxis[1]": 0,
        "TriggerPressed": "GestureWithin:TriggerFinger[0.5,1.0]"
    }
}

Look to "driver_null" section. Path to config file: C:\Program Files (x86)\Steam\config\steamvr.vrsettings

**Comment by jrbudda** [comment]
Still not working?
