### ISSUE TITLE
Keeps showing SteamVR Environment every second or so. 

### ISSUE THREAD

**Issue by darksinthe** [jrbudda/Vivecraft_110#73]
When I have my FPS counter on, it reads in the 90s then it flickers to steamVR background then back to minecraft, and the FPS shows around 50 then climbs back to 90s then flickers again, back to 50, and the process keeps repeating. doesnt matter if im moving, standing still, in a tiny room, i turned all the video options to super low and the same thing keeps happening. 

Every other VR game ive tried runs butter smooth on my 980 GTX. The strange thing is, the first time I opened vivecraft it flickered like twice and then stopped flickering and didnt flicker again for like the 20 minutes I was playing it. It even start ed raining in the game, and no flickers. This was when I had the graphics set on Fancy for most everything.

Now I have lowered the graphics to performance in nvidia control panel, turned every available graphic option that could alter FPS/GPU load in minecraft/optifine to fast or OFF, aaand I still get the same problem. Flickers to steam VR background environment once a second, sometimes faster. 

Super frustrated with this as I've tried everything I could think of. I even disabled tons of useless services even, and it still  does it.

My alteration of all those options and the fact that it once ran fine on Fancy makes me think there is something going on that has nothing to do with my computer not being able to 'handle' Vivecraft, and its really starting to annoy me that I can't seem to figure out what the heck it could possibly be.

**Comment by jrbudda** [comment]
Did you ever find a resolution to this?

**Comment by darksinthe** [comment]
Yes, I did figure it out. There was an environment variable in my windows files that was enforcing my RAM allocation in any Java app to be 128KB, so it was overriding any Xmx arguments I was putting into Minecraft.

**Comment by jrbudda** [comment]
Wow yea that would cause a performance problem or 2.
