### ISSUE TITLE
Cant launch [Linux]

### ISSUE THREAD

**Issue by CrimsonWolfM** [jrbudda/Vivecraft_110#75]
Hi! I tried to install this mod on Linux MInt Cinnamon, and after i lauched the game, it crashed. I have no additional mod, and tried reinstalling. I also have 64-bit java as recommended. If you can help, i'd be very glad. Thanks for noticing XD

crash-log:

---- Minecraft Crash Report ----
// Don't do that.

Time: 11/10/16 10:39 PM
Description: Initializing game

java.lang.UnsatisfiedLinkError: Unable to load library 'openvr_api': Native library (linux-x86-64/libopenvr_api.so) not found in resource path ([file:/home/crimsonwolf/.minecraft/libraries/com/mtbs3d/minecrift/1.10.2-Vivecraft-jrbudda-6r4/minecrift-1.10.2-Vivecraft-jrbudda-6r4.jar, file:/home/crimsonwolf/.minecraft/libraries/optifine/OptiFine/1.10.2_HD_U_C2/OptiFine-1.10.2_HD_U_C2.jar, file:/home/crimsonwolf/.minecraft/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar, file:/home/crimsonwolf/.minecraft/libraries/org/json/json/20140107/json-20140107.jar, file:/home/crimsonwolf/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar, file:/home/crimsonwolf/.minecraft/libraries/com/sun/jna/4.2.1/jna-4.2.1.jar, file:/home/crimsonwolf/.minecraft/libraries/de/fruitfly/ovr/JRift/0.8.0.0.1/JRift-0.8.0.0.1.jar, file:/home/crimsonwolf/.minecraft/libraries/net/aib42/mumblelink/JMumble/1.11/JMumble-1.11.jar, file:/home/crimsonwolf/.minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar, file:/home/crimsonwolf/.minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar, file:/home/crimsonwolf/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar, file:/home/crimsonwolf/.minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar, file:/home/crimsonwolf/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar, file:/home/crimsonwolf/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar, file:/home/crimsonwolf/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar, file:/home/crimsonwolf/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar, file:/home/crimsonwolf/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar, file:/home/crimsonwolf/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar, file:/home/crimsonwolf/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar, file:/home/crimsonwolf/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar, file:/home/crimsonwolf/.minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar, file:/home/crimsonwolf/.minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar, file:/home/crimsonwolf/.minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar, file:/home/crimsonwolf/.minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/home/crimsonwolf/.minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar, file:/home/crimsonwolf/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar, file:/home/crimsonwolf/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar, file:/home/crimsonwolf/.minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar, file:/home/crimsonwolf/.minecraft/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar, file:/home/crimsonwolf/.minecraft/libraries/com/mojang/realms/1.9.8/realms-1.9.8.jar, file:/home/crimsonwolf/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar, file:/home/crimsonwolf/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar, file:/home/crimsonwolf/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar, file:/home/crimsonwolf/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar, file:/home/crimsonwolf/.minecraft/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar, file:/home/crimsonwolf/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar, file:/home/crimsonwolf/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar, file:/home/crimsonwolf/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar, file:/home/crimsonwolf/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar, file:/home/crimsonwolf/.minecraft/versions/vivecraft-1.10.2-Vivecraft-jrbudda-6r4/vivecraft-1.10.2-Vivecraft-jrbudda-6r4.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:342)
	at jopenvr.JOpenVRLibrary.<clinit>(JOpenVRLibrary.java:17)
	at com.mtbs3d.minecrift.provider.MCOpenVR.init(MCOpenVR.java:285)
	at bcx.initMinecrift(Minecraft.java:4465)
	at bcx.an(Minecraft.java:751)
	at bcx.a(Minecraft.java:640)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:342)
	at jopenvr.JOpenVRLibrary.<clinit>(JOpenVRLibrary.java:17)
	at com.mtbs3d.minecrift.provider.MCOpenVR.init(MCOpenVR.java:285)
	at bcx.initMinecrift(Minecraft.java:4465)
	at bcx.an(Minecraft.java:751)

-- Initialization --
Details:
Stacktrace:
	at bcx.a(Minecraft.java:640)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.4.0-21-generic
	Java Version: 1.8.0_03-Ubuntu, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 173010160 bytes (164 MB) / 292171776 bytes (278 MB) up to 2120679424 bytes (2022 MB)
	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: vivecraft-1.10.2-Vivecraft-jrbudda-6r4
	LWJGL: 2.9.4
	OpenGL: Gallium 0.4 on AMD REDWOOD (DRM 2.43.0, LLVM 3.8.0) GL version 3.0 Mesa 11.2.0, X.Org
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7 CPU M 620 @ 2.67GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0 Mesa 11.2.0
	OpenGlRenderer: Gallium 0.4 on AMD REDWOOD (DRM 2.43.0, LLVM 3.8.0)
	OpenGlVendor: X.Org
	CpuCount: 4

**Comment by jrbudda** [comment]
The released version do not have support for linux. Please try the build in this thread https://github.com/jrbudda/minecrift/issues/241

**Comment by jrbudda** [comment]
closing due to better thread in other repo.
