### ISSUE TITLE
(Most) Audio not working

### ISSUE THREAD

**Issue by Shadaez** [jrbudda/Vivecraft_110#8]
Works fine on non-vr, and in vr in 7.2 release. Checked to make sure it wasn't coming out of a different audio source for some reason, I still get music and UI sounds but no monsters, environment, or block hits.

**Comment by Jonas-Mikkelsen** [comment]
I have the exact same issue

**Comment by KellyMahan** [comment]
Just got ViveCraft running here as well. No sounds except for music and ui.

**Comment by jrbudda** [comment]
Will hotfix as soon as I figure out what's wrong, this one is pretty major and what I get for never plugging my earbuds in when testing.

**Comment by jrbudda** [comment]
See if fixed

[vivecraft-1.10.2-Vivecraft-jrbudda-1r1-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/374305/vivecraft-1.10.2-Vivecraft-jrbudda-1r1-installer.exe.zip)

**Comment by jrbudda** [comment]
Check releases page for updated build including this fix.

**Comment by twigsta** [comment]
Sound now working but now I can't mine.

I can punch pigs though, which is a relief.

**Comment by jrbudda** [comment]
I cant reproduce the mining issue, are you clicking, swinging? singleplayer, multiplayer? creative or survival?

**Comment by twigsta** [comment]
Sorry jrbudda, I restarted and the problem went away.

**Comment by Shadaez** [comment]
Still happens sometimes, not sure why. I've had audio working then restart the game and it won't be. SteamVR stays on the entire time, so it shouldn't be an issue of audio devices changing.
