### ISSUE TITLE
Stuck on black screen during "End of Game" sequence

### ISSUE THREAD

**Issue by slicedlime** [jrbudda/Vivecraft_110#80]
I just finished a run to get to and kill the ender dragon I've been doing as a let's play. After entering the exit portal from the end, I simply ended up on a black screen, and could find no way to skip it from inside the VR environment. In the end I ended up taking off the headset and hitting escape to skip the sequence, at which point I properly loaded into my spawn again.

This is on version 1.10.2 v5 (I couldn't handle the roomscale running changes in v6). [Here's the video I captured](https://youtu.be/MHRvjOGGMvI).

**Comment by jrbudda** [comment]
Thanks, fixed in upcoming 1.11 release

**Comment by jrbudda** [comment]
Fixed in 1.11
