### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by Seegras** [jrbudda/Vivecraft_110#81]
While building with build.py:

Downloading: JRift-0.8.0.0.1.jar
Downloading: JMumble-1.11.jar
Downloading: JRiftLibrary-0.8.0.0.1-natives-linux.jar
Downloading: JMumbleLibrary-1.11-natives-linux.jar
ERROR: File is not a zip file

Turns out, all of them are 404 HTML documents. 

The (correct) files can be gotten from https://github.com/mabrowning/minecrift-repo/

**Comment by jrbudda** [comment]
I know the build.py for 1.11 works.
