### ISSUE TITLE
Forge mod jar - 1.10

### ISSUE THREAD

**Issue by fusionmc-evilscoop** [jrbudda/Vivecraft_110#82]
Hi,

Can you please release this as a jar and not an installer...

I use multimc for all my minecraft games (inc ftb and atlauncher) and need a forge jar or instructions for installing with a non standard launcher...
thx

**Comment by jrbudda** [comment]
Not possible. Vivecraft is a not a Forge mod and has to be installed as it's own profile. There is currently no Forge-integrated version of Vivecraft for 1.10+, only 1.7.10.

**Comment by tjmonk15** [comment]
Since forge compatible versions now exist for 1.10 and 1.11, can this be revisited? Would be nice to have a single jar (or a "mod" jar and a coremod jar) to drop into an existing pack.

**Comment by jrbudda** [comment]
no. vivecraft would have to be rewritten from scratch.

**Comment by fusionmc-evilscoop** [comment]
it very limiting to the default mc launcher...as i use technic, at and multimc this cannot be used on any of my servers
Good luck, so long

**Comment by Techjar** [comment]
The vanilla launcher can be used for any mod pack, you just have to point the game directory at the mod pack's directory. Is there any reason you can't use the vanilla launcher?

**Comment by fusionmc-evilscoop** [comment]
it sucks, it doesnt let you cleanly distribute a mod pack with updates to users
Its ugly, its not as easy to install stuff in compared to others...it was built without modding in mind and has had very little progress...
There is a reason why most mod packs, from dire to bevo have moved away from it :D

**Comment by jrbudda** [comment]
it CAN be a self contained forge mod. Right now it is not a Forge mod at all. Doing that requires re-writing it totally from scratch which I, for one, am just not going to do.

**Comment by fusionmc-evilscoop** [comment]
yip i know...ive hung round the discord for a v long time and here....we've evan had this discussion before :D
which is why i was saying, good luck, ive lost interest in this mod now.

**Comment by TheTrueForce** [comment]
I agree about the official launcher; it's a horribly designed pain in the arse.
Unlike Liteloader and Optifine, Vivecraft doesn't behave as a Forge mod. It's a custom version of Minecraft that includes Optifine and implements the Forge API. It does come as an installer for a reason.
AFAIK, FTB modpacks go through Curse, which effectively wraps the official launcher, so technically they do still use the vanilla launcher.
What launchers are you thinking of? I don't know of any launcher that can install Forge as a drop-in jar.

**Comment by fusionmc-evilscoop** [comment]
technic - with or without solder
you rename the universal to modpack.jar and drop in the bin dir

Multi mc, you right click the instance and just pick a forge version

atlauncher.....not made a pack for this....but its xml controlled

**Comment by TheTrueForce** [comment]
That makes a degree of sense.
