### ISSUE TITLE
Can't install the project after cloning my fork

### ISSUE THREAD

**Issue by Luckless** [jrbudda/Vivecraft_110#83]
I was curious about forking and installing this vivecraft 1.10 project. The README says it isn't possible for technical reasons.

I thought I'd open an issue so those reasons from the README could be outlined for curious developers.

My end goal is probably the same as other devs interested in this branch--forge support! I gotta try that pixelmon 5.0 in VR 👍

**Comment by jrbudda** [comment]
The reasons are you need a modified jar of the full game to do the mcp install properly and I do not feel comfortable hosting that on the internet publicly for copyright reasons. If you come by the discord channel I can get you a jar and the instructions go with it.

**Comment by Luckless** [comment]
Ah,

Understood.

I'll make my way by the channel next time I get the urge to tinker with
some code in my spare time
