### ISSUE TITLE
Game Crashing on the Mojang screen when launching

### ISSUE THREAD

**Issue by HeraYuuki** [jrbudda/Vivecraft_110#84]
So I installed the mod but whenever I try to launch it it just freezes when the mojang logo appears
Here's the output log:
http://pastebin.com/A8gP6UXZ

**Comment by jrbudda** [comment]
theres no error in your pastebin, are you affected by the nvidia driver issue as noted on the vivecraft site?

**Comment by HeraYuuki** [comment]
Ah! It was, Thank you!
