### ISSUE TITLE
Pixelmon Keyboard bug

### ISSUE THREAD

**Issue by zeshinumi** [jrbudda/Vivecraft_110#86]
While in pixelmon, when you go into a battle, every menu button press wants to bring up the keyboard in the vive.

**Comment by jrbudda** [comment]
ah yea, had this problem on 1.7

**Comment by jrbudda** [comment]
lets blindly assume its the same fix
[vivecraft-1.11.2-jrbudda-9alpha15-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/958282/vivecraft-1.11.2-jrbudda-9alpha15-installer.exe.zip)

**Comment by jrbudda** [comment]
let me know if it still does the thing where it rendering you inside your own head

**Comment by zeshinumi** [comment]
It was, I'll try that build soon as I get the chance to see if it fixes it

**Comment by jrbudda** [comment]
[vivecraft-1.10.2-Vivecraft-jrbudda-8alpha2-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/958298/vivecraft-1.10.2-Vivecraft-jrbudda-8alpha2-installer.exe.zip)

**Comment by zeshinumi** [comment]
The head thing is gone and fixed, but the keyboard thing is still happening. Is it because pixelmon allows for keyboard input in the battle screen, so that display kicks in?

**Comment by jrbudda** [comment]
yea they use something in their UI that inherits from GUITextField. When a GUITextField gets focus we have it pop open the keyboard. I have it filtered out in 1.7.10 in a really stupid way that must not be working for the newer pixelmon, will have to set up a special build to test it. thanks for your input.

**Comment by zeshinumi** [comment]
np!

**Comment by zeshinumi** [comment]
oh isis is in the discord, you might be able to ask him about it

**Comment by jrbudda** [comment]
Simple thing. This should do it.
[vivecraft-1.10.2-Vivecraft-jrbudda-8r2-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/966296/vivecraft-1.10.2-Vivecraft-jrbudda-8r2-installer.exe.zip)

**Comment by zeshinumi** [comment]
yep that worked!
