### ISSUE TITLE
Multi-mod conflict with Extra Utilities

### ISSUE THREAD

**Issue by TrypChangeling** [jrbudda/Vivecraft_110#87]
Extra Utilities, Flat Colored Blocks, and Random Things cause a crash on load.

And by that, I mean Extra Utilities and either Flat Colored blocks or Random Things, or both causes a crash

Extra Utilities by itself is fine, and Flat Colored Blocks and Random Things are both fine if Extra Utilities is not loaded.

I also had the same problem with Extra Utilities and Charset in Sky Factory 3, but not in an isolated environment.

**Comment by jrbudda** [comment]
could you possibly pastebin the fml-latest.log file from .minecraft/logs right after it crashes?

**Comment by TrypChangeling** [comment]
https://pastebin.com/E3MiwMpv

**Comment by nallar** [comment]
Optifine's transformer removes the `TextureMap.setTextureEntry(TextureAtlasSprite)` method, leaving only the two argument form, causing a NoSuchMethodError. At this point the game doesn't crash, but it later hits an NPE and crashes.

Workaround patch xml for ModPatcher: https://gist.github.com/nallar/cc5feb8d80371e21911ff281bdd1a41c

**Comment by jrbudda** [comment]
The real solution for us is to update the baked-in optifine version as optifine did fix this. I will work on that today.

**Comment by jrbudda** [comment]
This  is done in v9
