### ISSUE TITLE
Can't press enter in chat

### ISSUE THREAD

**Issue by nallar** [jrbudda/Vivecraft_110#88]
After installing the 1.10.2 r8 for forge, I can't push enter in chat.

Other keys on the vive keyboard work, but pushing enter does nothing so you can't send the message/command.

OS: Windows 10
Java: 8u121 64 bit
Keyboard layout: US

**Comment by jrbudda** [comment]
Ok sit tight we're totally revamping how we submit keypresses to GUIs for the next version, we'll see if that fixes it. Does it send the chat if you press 'done'?

**Comment by nallar** [comment]
> Does it send the chat if you press 'done'?

Nope :( Chat stays open with message, keyboard vanishes. Pressing enter on IRL keyboard also does nothing.

**Comment by jrbudda** [comment]
Give this a whirl. Fixed the bug preventing chat being sent, but also includes the new keyboard injector so things like the JEI search box should work again.

[vivecraft-1.10.2-Vivecraft-jrbudda-9pre-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/981709/vivecraft-1.10.2-Vivecraft-jrbudda-9pre-installer.exe.zip)

**Comment by nallar** [comment]
That works great. Thanks :)

Can't click on the JEI search box to try to enter text (clicking using trigger in general doesn't work with JEI buttons or the search box) so not sure if keyboard now works with it.

**Comment by Techjar** [comment]
Make sure the window is in focus, so it uses the awt.robot calls.

**Comment by nallar** [comment]
Good call, that was the problem.

Thanks for fixing this.
