### ISSUE TITLE
Can't start on fresh install

### ISSUE THREAD

**Issue by navarr** [jrbudda/Vivecraft_110#89]
Environment:  Windows 10 x64

Steps:
* Cleaned out .minecraft folder
* Started Launcher
* Logged in
* Started 1.11.2 (downloading all the required fields)
* Closed 1.11.2
* Closed Launcher
* Deleted logs
* Installed Vivecraft 1.11.2v9r1 (default options, only the launcher profile & 2gb of ram, confirmed minecraft path correct .minecraft)
* Started Launcher
* Started Vivecraft profile
* Crashed

latest log:[trunc]

**Comment by jrbudda** [comment]
There's no crash in this log file, can you check the crash-reports folder or launcher.log for the crash stack trace? And please put it on pastebin.

**Comment by navarr** [comment]
Oh, sorry about that!  I'll start over from clean.

latest.log: https://pastebin.com/raw/JvxUkfbU
launcher log: https://gist.githubusercontent.com/navarr/b05d77ed370943a11df5f9b589de8cd7/raw/13a14dedf902c743eaf82cefd8dffc2f0022df94/launcher_log.txt

Neither of these have an actual crash in them either.  There is no crash-reports folder.  

It goes not responding to ![](http://i.imgur.com/YCILgXu.png)

Any other ideas of how to get some debug info for you?

**Comment by jrbudda** [comment]
Do you happen to be using NVIDIA gpu driver 378.49?

**Comment by navarr** [comment]
378.78.

Using Riftcat/Vridge as HMD

**Comment by navarr** [comment]
I got another driver update recently and this issue is no longer occurring.
