### ISSUE TITLE
Scrolling in VR settings

### ISSUE THREAD

**Issue by denny99** [jrbudda/Vivecraft_110#9]
For some reason i'm not able to scroll down in the vr settings menu's. (keymappings, quickcommands)

**Comment by jrbudda** [comment]
See if fixed in 1r1

**Comment by denny99** [comment]
Nope, problem exists even in v2

**Comment by jrbudda** [comment]
dang, the window has focus? can you scroll using the right touchpad?

**Comment by denny99** [comment]
yes it has focus but i can't scroll. It seems to be impossible to scroll with controllers in any menu. The non vr menu's can be scrolled down the mouse.

**Comment by jrbudda** [comment]
finally fixed I think
