### ISSUE TITLE
Malisis Door Mods crash

### ISSUE THREAD

**Issue by zeshinumi** [jrbudda/Vivecraft_110#90]
I loaded with just the Malisis mod and core mod and it crashes on start up
pastebin: https://pastebin.com/EUnwCFQF
I don't know if this will help, but it seems there's been an issue with this mod and optifine in the paste. This error seen here seems to show they just detect if its optifine to get around it, maybe it's linked? https://github.com/sp614x/optifine/issues/461

**Comment by jrbudda** [comment]
For anyone else that gets this, you need to use MalisisCore 4.4.0+ with Vivecraft 1.10.2v9+. Modpacks might not include this version so get manually from curse.
