### ISSUE TITLE
Mouse not captured for Chisels & Bits' radial menu in seated mode

### ISSUE THREAD

**Issue by mracsys** [jrbudda/Vivecraft_110#92]
Chisels & Bits has a radial menu that pops up when holding left Alt while the player holds a C&B item. It displays fine, but in seated mode the options can't be selected because the cursor still moves the player instead of moving around the menu. With keyhole > 0 I can select the left-most and right-most options on the wheel only. With keyhole = 0 I can't select anything.

Minecraft 1.10.2
Forge 12.18.3.2281
[Chisels & Bits 12.12](https://minecraft.curseforge.com/projects/chisels-bits/files)
Vivecraft 1.10.2v9
[fml-client-latest.txt](https://github.com/jrbudda/Vivecraft_110/files/985545/fml-client-latest.txt)

**Comment by jrbudda** [comment]
Sounds like they're displaying a interactive screen without actually popping up a 'screen' in the normal sense, and just drawing on HUD instead and capturing mouse events. I'm not sure that we can detect or fix that.

**Comment by mracsys** [comment]
From what I can tell it's not doing anything special on the rendering side. It's extending GuiScreen from net.minecraft.client.gui and overriding the drawScreen method, but vanilla classes do this too. I'll dig into the keybindings to see what is going on there. It has to detect the active item as a C&B item somewhere.

**Comment by jrbudda** [comment]
oh ok, so long as it's setting mc.currentScreen we should be picking it up and doing the appropriate mouse/cursor things.

**Comment by mracsys** [comment]
Looks like I was wrong. See below for relevant code to start drawing the gui (lines 556 - 570 in mod.chiselsandbits.core.ClientSide).

    if ( wasVisible == false )
    {
        ChiselsAndBitsMenu.instance.mc.inGameHasFocus = false;
        ChiselsAndBitsMenu.instance.mc.mouseHelper.ungrabMouseCursor();
    }

    if ( ChiselsAndBitsMenu.instance.mc.inGameHasFocus )
    {
        KeyBinding.unPressAllKeys();
    }

    final int k1 = Mouse.getX() * res.getScaledWidth() / ChiselsAndBitsMenu.instance.mc.displayWidth;
    final int l1 = res.getScaledHeight() - Mouse.getY() * res.getScaledHeight() / ChiselsAndBitsMenu.instance.mc.displayHeight - 1;

    net.minecraftforge.client.ForgeHooksClient.drawScreen( ChiselsAndBitsMenu.instance, k1, l1, event.getPartialTicks() );

mc.currentScreen is never touched by the mod or by Forge. I'm guessing this is done for the fade in/out effect.

Is Vivecraft overriding mc.mousehelper.ungrabMouseCursor?

**Comment by Techjar** [comment]
Yeah when inGameHasFocus we're forcibly re-grabbing the mouse, though I can't remember why.

**Comment by mracsys** [comment]
I made a workaround for anyone else that runs into this. The only different behavior compared to regular Chisels & Bits is the menu key is pressed once to open it instead of being held down. To select a tool/bit mode, left-click it. You can also press Esc to close the menu.

The attached patch files are valid against Chisels & Bits 12.12 for Minecraft 1.10.2 [(github)](https://github.com/AlgorithmX2/Chisels-and-Bits/tree/1.10.2).
[chisels_and_bits_vivecraft_patch-mod.chiselsandbits.core.ClientSide.txt](https://github.com/jrbudda/Vivecraft_110/files/999786/chisels_and_bits_vivecraft_patch-mod.chiselsandbits.core.ClientSide.txt)
[chisels_and_bits_vivecraft_patch-mod.chiselsandbits.client.gui.ChiselsAndBitsMenu.txt](https://github.com/jrbudda/Vivecraft_110/files/999787/chisels_and_bits_vivecraft_patch-mod.chiselsandbits.client.gui.ChiselsAndBitsMenu.txt)

I'm leaving the issue open in case you guys want to address this somehow in Vivecraft.

**Comment by mracsys** [comment]
This has been resolved. Anyone looking for this fix should compile Chisels & Bits from source until a new release drops. Note that this fix is only for Minecraft 1.10.2. I have not checked the 1.11 version.
