### ISSUE TITLE
Unable to select anything in menu after HUD "body" mode enabled

### ISSUE THREAD

**Issue by HIghCommander540** [jrbudda/Vivecraft_110#93]
I was experimenting with the different HUD modes. I cycled through the first three and then clicked again to "body" mode. I am unable to interact with the in-game menu anymore. It won't even give me a cursor.

I was actively playing the game at the time.

**Comment by jrbudda** [comment]
I thought we disabled that mode, sorry.

**Comment by jrbudda** [comment]
I did fix the bug, but also disabled that mode as it is still kinda broken.
