### ISSUE TITLE
Glitchy Nether and other dimensions on 10pre6 forge

### ISSUE THREAD

**Issue by Chimera245** [jrbudda/Vivecraft_110#95]
When going to the Nether, or any other dimension, (I tested Nether, The End, and Extra Utilities 2's Deep Dark) The chunks generate weird.

There will be floating 16x16x16 cubes all of one random block floating around the world. The "real" nether will still be sort-of there, like you will see entities standing on invisible ground, and you can be hurt by invisible fire or lava, but you can't interact with anything but the floating cubes of random material. 

If you try to break a block from the floating glitch-cubes, you may or may not see the block disappear, though the cursor will still point to the next block in, and you can still move into that space if there's room for you.

If you try to place a block, several things might happen.
-The block places normally.
-The block places, but turns into whatever block is supposed to be there. (usually netherrack)
-The block replaces block you're pointing at, instead of being placed adjacent to it.
-If the block is placed against a floating glitch-cube, the entire 16^3 area adjacent becomes filled with the block you tried to place, which might lead to suffocation damage, depending on where you're standing at the time.

The bottom 16 blocks of each chunk seem to generate normally in most cases, and some mod ores generate normally, suspended in "midair" where there's supposed to be ground all around them, but it's invisible to you.

Generally, the cubes are made of some block that is normal for the dimension, for example, I most often found netherrack, nether quartz ore, lava, fire, mushrooms, etc. in the nether, or end stone, bedrock, obsidian, Draconium ore, etc. in The End, but I would also find podzol, torches, polished diorite, wooden stairs, etc. scattered here and there.

The sky will retain the Overworld sun/moon/stars look, and the current biome will read as whatever the Overworld's biome is for your location, instead of reading "Hell" or "The End".

This happens even when visiting a dimension that has already been generated in a previous version of Vivecraft. 

This happened regardless of which combination of mods I had in my mods folder, and even with no mods at all. (except Vivecraft, of course)

It does not happen with the "vanilla-only" install of 10pre6, only the Forge one.
Downgrading to an earlier version of Vivecraft fixes it. (and takes away the backpack-switching mechanic, and reverses my swiping across the hotbar on the touchpad, and takes away two-handed tinkers' bows, and generally makes me sad.)

Playing non-Vivecraft Forge with an empty mod folder generates dimensions normally.
Playing non-Vivecraft Forge with a full mod folder crashes my game, so I can't check what the Nether looks like.

**Comment by jrbudda** [comment]
Will test. Cannot think of what would have caused this.

"Playing non-Vivecraft Forge with a full mod folder crashes my game, so I can't check what the Nether looks like."

That's odd, same version?

**Comment by Techjar** [comment]
Also we'd like a crash log from that.

**Comment by jrbudda** [comment]
No we don't send it to lex :)

**Comment by Techjar** [comment]
Oh I misread, non-*Vivecraft* forge, not non-*Forge* Vivecraft.

**Comment by jrbudda** [comment]
Tho if you do post one, we could prolly tell you what's wrong.

**Comment by Techjar** [comment]
If you could also give us the fml-client-latest.log from when you get that weird nether chunk issue, it probably be quite helpful.

**Comment by jrbudda** [comment]
ive reproduced it

**Comment by jrbudda** [comment]
https://gyazo.com/106cfa84be4f6d2ca1d83d07f63c3ab9

**Comment by Techjar** [comment]
See if this fixes your issue.
[vivecraft-1.10.2-jrbudda-10pre7-installer.exe](https://qimg.techjargaming.com/f/I4mIq99m.exe)

**Comment by Chimera245** [comment]
Thanks, sorry it took so long to respond. Right after I posted that, I went to sleep, then went to work, then got home, saw it was fixed, then got lost in minecraft for hours.

Since it's working now, I assume you don't need me to post my logs anymore?

Also, about the crashing, I think it's because Vivecraft has built-in Optifine. I don't otherwise have that installed, so my mods must be too much for my PC to handle without, I guess? I dunno. I figure running VR with fancy graphics turned on would be more than Optifine would make up for, but what do I know?

**Comment by Techjar** [comment]
Yeah, we don't need the logs from the Vivecraft crash as it seems to be resolved now (we actually reproduced it and got the log ourselves). Amazing how one little error brings the whole thing crashing down. However, I'd like to see the log from the non-Vivecraft crash just out of curiosity, as I've never heard of anyone crashing only *without* Vivecraft. No promises that I'll be able to provide you a fix though.

**Comment by Chimera245** [comment]
[crash-2017-06-01_10.25.11-client.txt](https://github.com/jrbudda/Vivecraft_110/files/1049464/crash-2017-06-01_10.25.11-client.txt)

**Comment by jrbudda** [comment]
java.lang.OutOfMemoryError: Java heap space

you need more rams.

**Comment by Chimera245** [comment]
I thought I had 4GB set... Is that only when I use Vivecraft somehow?

**Comment by jrbudda** [comment]
yea its specified in the profile. our installer sets it to 2 or 4, I don't think Forge's installer specifies anything.

**Comment by Chimera245** [comment]
Ohhh... I forgot different profiles could even HAVE different RAM allocations... I somehow got to thinking that was a "per minecraft installation" thing. So all I have to do is tweak the non-vr forge profile, and it should work, right?

**Comment by jrbudda** [comment]
yup! we allocate 4gb to forge.

**Comment by Chimera245** [comment]
It works! Thanks a lot.

I have a friend who also has been crashing, who I've been wanting to play together with, and now, (presumably) we can.

It seems Minecraft empathizes with me. I started it up, non-vr, and my splash text was "Yaaay!"
