### ISSUE TITLE
Probably not Vivecraft's fault, but I'm out of other ideas...

### ISSUE THREAD

**Issue by Chimera245** [jrbudda/Vivecraft_110#96]
I tried to play with a friend of mine, over LAN, and forge wouldn't let her connect to me, saying "fatally missing blocks and items". 

We spent hours googling the error, and the main culprits seemed to be either differences in the language settings, or mismatched versions of mods. 

Both our computers are, and always have been set to English(US), both on the system, and in Minecraft itself, and her computer's mod folder was copied directly from my computer, so everything is exactly the same version.

The only difference is she doesn't have Vivecraft, which adds climbing claws and jump boots. I am fairly certain that those items are just vanilla shears and leather boots with a bunch of NBT shenanigans going on, rather than separate items in the code, but at this point, It's the only thing I can think of as to why she's getting this message.

It's not, right? I can't be the only person to try to LAN with a non-vr friend since the Climbeymotion update...

**Comment by CoolTrainerSarah** [comment]
I just had this happen. In my case, it was mismatched mod configurations. One of the mods on the server has a set of items enabled that the client has disabled in their config. Try copying the server mod configs to the problematic client.

**Comment by Chimera245** [comment]
Nope, I also copied the config folder from my computer to hers when I copied the mod folder. And once we first had this issue, and googled around a while, I also copied every folder I had that she didn't, except VR related ones. Like the EnderIO folder and the JourneyMap folder that were created outside of the mods/config folders.

**Comment by jrbudda** [comment]
Are you trying to do a LAN-hosted game? or a Dedicated Forge server on your lan?

**Comment by Techjar** [comment]
Sounds like you're using the integrated LAN server. Not sure why you're getting that error, but in any case, there are other problems with using the integrated LAN server, like odd behavior for other players to due changes we make to server-side code on the client. Also, since you can't install VFE on a client, other players won't see your arm movements.

If you want to play with others over LAN, simply host a dedicated Spigot (for vanilla) or Forge server on your PC and install VSE or VFE respectively. This way everything will behave correctly for all players and others will see your arm movements.

**Comment by Chimera245** [comment]
Yes, I was trying to play with my single player world "open to LAN" if that's what you mean.

Would this definitely solve my "missing blocks and items" problem, or do I still need to figure out where that's coming from first?

I've successfully played in VR open to LAN before, modded with forge, with this same person, on these same computers. It was the 1.7.10 version, and it was a while ago, (I think about when the wavy visual effect for being underwater/in a portal was new...)

Has something been changed/added to either 1.10.2 version, or Vivecraft in general that would suddenly make this start happening?

**Comment by Chimera245** [comment]
If I'm understanding this right:
-Server needs Vivecraft Forge Extension in its mod folder, not Non-VR companion.
-Other Player needs Non-VR companion in their mod folder, not VFE.
-I don't need either one in my mod folder, just need Vivecraft installed.

Is that right?

**Comment by Chimera245** [comment]
Oh, after installing mods into the server folder, I started it up, and now I'm getting this message:

There are 2 missing blocks and items in this save.
If you continue the missing blocks/items will get removed.
A world backup will be automatically created in your saves directory.

Missing Blocks/Items:
minecraft:drinkme_bottle
minecraft:eatme_cake

Do those come from Vivecraft? I've gotten them a couple of times, and they seem to temporarily change your scale in the world. NEI lists their mod as "minecraft" the way it does for Climb claws and Jump boots... If they are from Vivecraft, I'm not sure why it thinks the claws and boots are okay, but not the bottle and cake, but I bet these are the "missing blocks and items" that my friend was having issues with...

**Comment by jrbudda** [comment]
Your best bet is going to be playing on a server, Forge server gets VFE mod.  You install Vivecraft, and your friend installs non-vr companion. This way you get all the animations and stuff that are not supported on open-to-lan.
