### ISSUE TITLE
Random Teleports

### ISSUE THREAD

**Issue by captroper** [jrbudda/Vivecraft_110#97]
I have been hosting a server for a while and playing in vr with a friend who was not using the non vr companion. Another friend hopped on today with vivecraft and the game repeatedly and seemingly randomly teleported us to each other (either him to me or me to him). I am running direwolf20 modpack with the server plugin and this has never happened with the friend playing on the monitor.

This is on 9r3

**Comment by jrbudda** [comment]
Are you both using teleport movement?

**Comment by captroper** [comment]
Yes, but to be clear we were teleported to each other from fairly disparate areas. Like across an entire map, and then up and down a few hundred blocks another time

**Comment by jrbudda** [comment]
I understand. does the problem disappear if one or both of you are in free-move mode?

**Comment by captroper** [comment]
I'm not sure, unfortunately we're both pretty susceptible to motion sickness using free-move. I'd try it, but because it only happened 4 times over the course of 2 hours I'm reticent to try.

**Comment by jrbudda** [comment]
Okay, any idea if the jump was actually randomly timed? or the normal teleport movement doing the wrong thing?

**Comment by captroper** [comment]
I'm not 100% sure. I *think* one of the times I did teleport at the same time. One of the times I was clicking on the Journeymap map (a mod in direwolf20), one of the times I was mining the block above me and suddenly ended up 100ish blocks up and a few horizontal, and I don't know what my friend was doing the time(s) that he teleported to me.

**Comment by Techjar** [comment]
What was your friend doing at the time you got teleported? We're trying to figure out if this is actually random or if it only happens when *someone* teleports.

**Comment by captroper** [comment]
Understood. I'm not sure, I can update the post after talking to him.

**Comment by Techjar** [comment]
You are actually getting teleported to eachother (or at least nearby), and not just some random location, correct?

**Comment by captroper** [comment]
Correct. Suddenly there are two people in exactly the same spot.

**Comment by captroper** [comment]
He said that each time he tpd to me he was trying to teleport (move)

**Comment by Techjar** [comment]
Wait, so when he tried to teleport, he got teleported to you instead? Or you got teleported to him?

**Comment by captroper** [comment]
Apologies, occassionally he would try to teleport with the trigger to move slightly forward and would instead teleport to wherever I was.

**Comment by captroper** [comment]
The problem appears to no longer be present in the latest vivecraft version.

**Comment by jrbudda** [comment]
I dont think we did anything to fix this

**Comment by captroper** [comment]
Certainly possible that it still exists but is just so sporadic that we haven't seen it yet. That being said, we've played at least 7-8 hours without seeing it. Neither of us changed any mods, minecraft version, resource pack, or anything other than the vivecraft version. I may have updated the VFE on the server, but I unfortunately do not recall.
