### ISSUE TITLE
Can't Fire Tinker's Construct Long Bow

### ISSUE THREAD

**Issue by captroper** [jrbudda/Vivecraft_110#98]
Sorry to keep bombarding this thread with issues, just figured it would be better to report than say nothing. I'm having an issue where I can't fire the Long Bow from Tinker's Construct in the Pre-Release version. When equipped in an inventory slot (where you use all items) and accessed the bow appears in the left hand instead of the right hand. Holding down the use button makes the arrow bob back and forth slightly but it never fires. I have not been able to get it to nock and fire with roomscale controls either. The issue presents itself both with and without a texture pack. The issue was also present in the 9r3 version, but it would render the bow in both hands instead of just one. 

This is the bow in question: http://tinkers-construct.wikia.com/wiki/Longbow and it does work with normal modded forge minecraft (not vivecraft)

**Comment by jrbudda** [comment]
If it's rendering in the left hand then it's being detected as a 'bow' and should work in roomscale like normal minecraft bows. The motion should be the same even if the graphics do not match.

**Comment by Chimera245** [comment]
I ran into this too until I put vanilla arrows in my inventory
It's like the roomscale bow mechanic doesn't recognize non-vanilla arrows, but as long as it is there, you can fire the Tinkers' arrow if it's in an inventory slot before the vanilla one.
Basically:
-If there's no arrow, nothing happens.
-If there's a Tinkers' arrow, nothing happens.
-If there's a vanilla arrow, you can fire it out of the Tinkers' bow.
-If there are both, and the vanilla arrow comes first in the inventory, you can fire a vanilla arrow.
-If there are both, and the Tinkers' arrow comes first, you'll hold a vanilla arrow in your main hand, and when you nock it on the Tinkers' bow, it'll suddenly be a Tinker's arrow, which can then be fired from the bow normally.

At least that's my experience.

**Comment by captroper** [comment]
Very interesting, I'll give this a shot. What do you mean by "first" in terms of inventory? Furthest to the left?

**Comment by jrbudda** [comment]
Yea, of course the tinkers arrows dont inherit from the vanilla arrow, because that would make my life easier.

**Comment by Chimera245** [comment]
Yeah, there's a technical page on the official Minecraft wiki, that explains the order of inventory slots, but I believe it starts by looking in your hotbar, from left to right, then the top row from left to right, then second row, then third, then armor slots. (not that arrows can actually go in armor slots...) I'm not sure where the off-hand slot factors in, since I learned about this before it was added...

**Comment by jrbudda** [comment]
I guess i could make a slightly more intelligent check for tinkers arrows, which is literally looking at the class name and seeing if it has 'arrow' in it.

**Comment by captroper** [comment]
I can confirm that Chimera's trick worked. However, I can't seem to figure out how to get the arrow to shoot further. In the base game it works based upon the amount of time you hold down the use button with a little aiming reticule square getting progressively smaller to show aim. I tested this one about 20-25 times trying pulling further, holding the trigger longer and combinations of the two in escalations from my hand on the same place it started with the arrow to as far as I could reach and 1 second to 25 seconds. Neither length nor timing had any effect on where the arrow landed.

**Comment by jrbudda** [comment]
Not sure if that's something we can support. Depends on how its coded.

**Comment by captroper** [comment]
Just figured I'd let you know! It definitely works, the bow shoots just fine, just over a shorter distance than anticipated. (And I might add as someone who hadn't yet tried roomscale archery in MC, it's pretty sweet so thanks!)

**Comment by Chimera245** [comment]
I know the bow limb material has an effect on range. (Pulsating Iron from Ender IO is awesome for bows...)

Did you mean "the arrows didn't go as far as I thought they would, go figure"? Or do you mean "the arrows didn't go as far from this exact same bow in VR as they did while not in VR"? 

Cuz if it's comparing VR to non-VR, I got nothin'.
But if it's just a shortcoming of your bow, look through "Materials and You" for something with a good range multiplier, like Pulsating Iron.

**Comment by captroper** [comment]
The arrows do not behave in the same manner as the same arrows with the same bow in non-vr. In non-vr there is a square reticule that controls the distance/speed and the longer you hold down the button the smaller it gets and the further / more precise the arrow travels in a straight line. In VR the arrow arcs a little bit and then falls.

**Comment by jrbudda** [comment]
Looking at the code i'm surprised the distance isn't being handled properly, but there's a lot of factors at work.

Try this build, it should maybe detect mod arrows. The offhand slot is checked first.

[vivecraft-1.10.2-jrbudda-10pre8-installer.exe.zip](https://github.com/jrbudda/Vivecraft_110/files/1065118/vivecraft-1.10.2-jrbudda-10pre8-installer.exe.zip)

**Comment by captroper** [comment]
Mod arrows are detected now without other arrows needing to be present. I tried it with the mod arrow both in my inventory and on the quickbar and it worked both times.

**Comment by Chimera245** [comment]
Weird, my bow goes so far and straight in vr, that I can barely notice the arc. Like, I can literally shoot an arrow out of my render distance in the right circumstances.

**Comment by captroper** [comment]
hmmm.... is it a long bow? what are the materials? how long are you keeping it drawn for? are you pulling your arrow hand back particularly far? Do you have the square aiming reticule like in non vr? finally, what version of mc and what version of vivecraft?

**Comment by Chimera245** [comment]
Yes, longbow. Two Pulsating Iron limbs, Dark Steel Plate, I think the bowstring is ordinary string, but I can't remember. (And if it matters, the arrows are Dark Steel head, sugar cane shaft, and feather fletching) I never really timed the draw, I usually just let go when I feel like I've aimed properly which can take several seconds sometimes. I usually have the bow hand straight out, and the arrow/string hand maybe six inches behind my head? I don't have the square, I honestly forgot it existed until I read this thread because it's been so long since I played out of VR. 1.10.2 Minecraft and 10pre9 Vivecraft. (I downloaded the new update, but haven't played it yet...)

**Comment by captroper** [comment]
Hmm... Ok, those materials are probably outside of my tech range right now. The arrows shouldn't matter as I was having the same issue with normal arrows as I was with the modded ones. I'll give it another shot waiting several seconds and trying to match your position, but I've updated to the latest version so there may be variance there.

**Comment by captroper** [comment]
It is working as of the latest version.

**Comment by captroper** [comment]
Spoke too soon, issue is still present. Didn't change anything in the interim.
